import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--autoplay-policy=no-user-gesture-required', '--ignore-gpu-blocklist'] });
const p = await b.newPage({ viewport: { width: 1280, height: 720 } });
const errs = []; p.on('pageerror', e => errs.push(e.message)); p.on('console', m => { if (m.type() === 'error' || m.type() === 'warning') errs.push(m.type() + ': ' + m.text()); });
await p.goto('file://' + process.cwd() + '/dist/index.html');
await p.waitForFunction(() => window.LD && LD.Main && LD.Main.ready, null, { timeout: 60000 });
await p.mouse.click(300, 300); await p.waitForTimeout(500);
const r1 = await p.evaluate(() => ({ unlocked: LD.Audio.unlocked, ctx: !!LD.Audio.ctx, state: LD.Audio.ctx && LD.Audio.ctx.state, music: LD.Music.playing, mode: LD.Music.mode }));
await p.waitForTimeout(2500);
const r2 = await p.evaluate(() => { LD.Settings.set({ tutorial: false }); LD.Main.startNewGame({ name: 'Audio', difficulty: 'normal', seed: 3 }); const D = LD.Debug, G = LD.G, hub = Object.values(G.structures).find(s => s.id === 'hub'); D.giveAll(500); D.unlockAll(); for (let i = 0; i < 6; i++) D.place('conveyor_wood', 0, hub.x + 3, hub.y + i - 1); D.place('stone_furnace', 0, hub.x + 4, hub.y); D.place('steam_engine', 0, hub.x + 4, hub.y + 2); const f = Object.values(G.structures).find(s => s.id === 'stone_furnace'); LD.Sim.Economy.setRecipe(f.uid, 'smelting_copper_ore'); D.ff(10); const names = ['ui_click', 'build_place', 'build_done', 'research_done', 'wave_warning', 'shot_cannon', 'shot_laser', 'enemy_die', 'excavated', 'weather_storm']; names.forEach(n => LD.Audio.play(n)); return { music: LD.Music.playing, mode: LD.Music.mode, stats: LD.Audio.stats, furnace: f.state }; });
await p.waitForTimeout(2500);
const r3 = await p.evaluate(() => { for (let i = 1; i < 5; i++) { LD.Debug.unlockLayer(i); LD.Main.switchLayer(i); } LD.Main.switchLayer(0); return { stats: LD.Audio.stats, music: LD.Music.playing, mode: LD.Music.mode, layer: LD.Music.layerIdx }; });
await p.waitForTimeout(1500);
const r4 = await p.evaluate(() => { LD.Main.toMenu(); return { music: LD.Music.playing, mode: LD.Music.mode }; });
await p.waitForTimeout(2000);
const r5 = await p.evaluate(() => ({ music: LD.Music.playing, mode: LD.Music.mode, stats: LD.Audio.stats }));
console.log(JSON.stringify({ r1, r2, r3, r4, r5 }, null, 1));
console.log(errs.length ? 'ERRORS:\n' + errs.join('\n') : 'no errors');
await b.close();
