import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const p = await b.newPage({ viewport: { width: 1600, height: 900 } });
const errs = []; p.on('pageerror', e => errs.push(e.message)); p.on('console', m => { if (m.type() === 'error') errs.push(m.text()); });
await p.goto('file://' + process.cwd() + '/dist/index.html');
await p.waitForFunction(() => window.LD && LD.Main && LD.Main.ready, null, { timeout: 60000 });
await p.evaluate(() => { LD.Settings.set({ tutorial: true }); LD.Main.startNewGame({ name: 'Fix', difficulty: 'normal', seed: 11 }); });
await p.waitForTimeout(600);
const r1 = await p.evaluate(() => { const G = LD.G, hub = Object.values(G.structures).find(s => s.id === 'hub'); const list = LD.Sim.Economy.availableRecipes(hub.uid).map(r => r.id); LD.Debug.give(0, 'stick', 10); LD.Debug.give(0, 'stone', 5); LD.Debug.give(0, 'plant_fiber', 5); LD.Sim.Economy.setRecipe(hub.uid, 'hand_arrow_stone'); LD.Sim.Economy.setJobs(hub.uid, 1); LD.Debug.ff(20); return { hubRecipes: list, arrows: G.inv[0].arrow, sticks: G.inv[0].stick, state: hub.state, reason: hub.reason, jobs: hub.jobs }; });
await p.evaluate(() => { const hub = Object.values(LD.G.structures).find(s => s.id === 'hub'); LD.Sim.Economy.setJobs(hub.uid, null); LD.Debug.ff(20); });
const r2 = await p.evaluate(() => { const hub = Object.values(LD.G.structures).find(s => s.id === 'hub'); return { arrows: LD.G.inv[0].arrow, state: hub.state, jobs: hub.jobs }; });
await p.evaluate(() => { const hub = Object.values(LD.G.structures).find(s => s.id === 'hub'); LD.UI.Panel.select(hub.uid); });
await p.waitForTimeout(400); await p.screenshot({ path: 'tools/out/40_hub_panel.png' });
await p.evaluate(() => { LD.UI.Panel.select(null); LD.UI.Build.setMode('hand'); }); await p.waitForTimeout(400); await p.screenshot({ path: 'tools/out/41_hand_mode.png' });
await p.evaluate(() => { LD.UI.Build.setMode('normal'); LD.Debug.event('fog', 0); LD.Debug.ff(3); }); await p.waitForTimeout(500); await p.screenshot({ path: 'tools/out/42_fog_a.png' });
await p.evaluate(() => { LD.Render.panBy(240, 0); }); await p.waitForTimeout(400); await p.screenshot({ path: 'tools/out/43_fog_b.png' });
const tut = await p.evaluate(() => { const f = document.querySelector('.tut-fold'); if (!f) return 'no fold button'; f.click(); return document.querySelector('.tut-card').className; });
await p.waitForTimeout(300); await p.screenshot({ path: 'tools/out/44_tut_folded.png' });
console.log(JSON.stringify({ r1, r2, tut }, null, 1)); console.log(errs.length ? 'ERRORS ' + errs.join('\n') : 'no errors');
await b.close();
