// Visual review shots: node tools/shots.mjs
import { chromium } from 'playwright';
import path from 'node:path'; import fs from 'node:fs'; import { fileURLToPath } from 'node:url';
const here = path.dirname(fileURLToPath(import.meta.url)), dist = path.join(here, '..', 'dist', 'index.html'), out = path.join(here, 'out'); fs.mkdirSync(out, { recursive: true });
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
const errors = []; page.on('pageerror', e => errors.push(e.message + '\n' + (e.stack || '').split('\n').slice(1, 4).join('\n'))); page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
await page.goto('file://' + dist);
await page.waitForFunction(() => window.LD && LD.Main && LD.Main.ready, null, { timeout: 60000 });
await page.evaluate(() => { LD.Settings.set({ tutorial: false }); LD.Main.startNewGame({ name: 'Revisión', difficulty: 'normal', seed: 7 }); });
await page.waitForTimeout(600);
const shot = async (name) => { await page.waitForTimeout(350); await page.screenshot({ path: path.join(out, name + '.png') }); };
await page.evaluate(() => {
  const D = LD.Debug, G = LD.G, hub = Object.values(G.structures).find(s => s.id === 'hub'); D.giveAll(2000); D.unlockAll();
  const x = hub.x, y = hub.y;
  const P = (id, dx, dy, rot) => D.place(id, 0, x + dx, y + dy, rot || 0);
  for (let i = -8; i < 12; i++) P('conveyor_iron', i, 4);
  for (let i = -8; i < 12; i++) P('cable_copper', i, -2);
  for (let i = -8; i < 12; i++) P('pipe_steel', i, 8);
  P('stone_furnace', -6, 5); P('bronze_forge', -4, 5); P('blast_furnace', -1, 5); P('crusher', 3, 5); P('assembler', 6, 5); P('electric_furnace', 9, 5); P('lathe', 11, 5);
  P('steam_engine', -8, -5); P('coal_plant', -5, -5); P('water_wheel', 6, -5); P('windmill', 9, -5); P('battery', 12, -5); P('solar_panel', 4, -5);
  P('well', -8, 9); P('tank_steel', -6, 9); P('pump_hand', -3, 9); P('tank_iron', 0, 9); P('chemical_plant', 2, 9); P('refinery', 6, 9);
  P('watchtower', -10, 0); P('ballista', -10, 2); P('cannon_turret', -12, -2); P('laser_turret', -10, 6); P('tesla_coil', -12, 6); P('plasma_turret', -14, 2);
  for (let i = -16; i < -12; i++) { P('stone_wall', i, -4); P('steel_wall', i, 10); }
  P('woodcutter', 14, 0); P('gather_hut', 14, 3); P('warehouse_stone', 14, -4); P('study_table', 12, 1); P('lab_basic', 16, 6);
  P('fission_reactor', -8, 13); P('cooling_tower', -5, 13); P('fusion_reactor', 0, 13); P('nano_forge', 5, 13); P('shaft_coal', 10, 13); P('borer_electric', 14, 13);
  D.ff(30);
  LD.Render.setCam(0, (x + 1.5) * 48, (y + 4) * 48, 1.6);
});
await shot('10_showcase_noon');
await page.evaluate(() => LD.Render.setCam(0, (LD.G.view.cam[0].x), (LD.G.view.cam[0].y), 3));
await shot('11_showcase_zoom3');
await page.evaluate(() => { LD.G.time.t = 180; LD.Debug.ff(2); });
await shot('12_showcase_dusk');
await page.evaluate(() => { LD.G.time.t = 330; LD.Debug.ff(2); });
await shot('13_showcase_night');
await page.evaluate(() => { LD.Debug.event('rain', 0); LD.Debug.ff(3); });
await shot('14_rain');
await page.evaluate(() => { LD.Debug.event('clear', 0); LD.Debug.unlockLayer(1); LD.Main.switchLayer(1); const c = LD.World.centre(1); LD.Debug.place('borer_electric', 1, c.x + 8, c.y - 1); LD.Debug.place('mine_gallery', 1, c.x - 6, c.y + 3); for (let i = -6; i < 8; i++) LD.Debug.place('conveyor_iron', 1, c.x + i, c.y + 2); LD.Debug.ff(20); LD.Render.setCam(1, c.x * 48, c.y * 48, 1.4); });
await shot('15_caves');
await page.evaluate(() => { LD.Debug.unlockLayer(4); LD.Main.switchLayer(4); const c = LD.World.centre(4); LD.Render.setCam(4, c.x * 48, c.y * 48, 1.2); LD.Debug.ff(3); });
await shot('16_core');
await page.evaluate(() => { LD.Main.switchLayer(0); LD.Debug.spawnWave(0); LD.Debug.ff(60); const e = LD.Sim.Defense.enemiesIn(0)[0]; if (e) LD.Render.setCam(0, e.x * 48, e.y * 48, 2); });
await shot('17_enemies');
await page.evaluate(() => { const hub = Object.values(LD.G.structures).find(s => s.id === 'hub'); LD.UI.Panel.select(Object.values(LD.G.structures).find(s => s.id === 'blast_furnace').uid); LD.Render.setCam(0, (hub.x + 1.5) * 48, (hub.y + 4) * 48, 1.6); });
await shot('18_panel');
await page.evaluate(() => { LD.UI.Panel.select(null); LD.UI.Encyclopedia.open('techs'); });
await shot('19_techtree');
await page.evaluate(() => { LD.UI.Encyclopedia.close(); LD.UI.Stats.open(); });
await shot('20_stats');
await page.evaluate(() => { LD.UI.Stats.close(); LD.UI.Build.open(); });
await shot('21_palette');
await page.evaluate(() => { LD.UI.Build.close(); LD.Main.toMenu(); });
await page.waitForTimeout(1500);
await shot('22_menu');
await page.evaluate(() => LD.UI.Menu.newGame && LD.UI.Menu.newGame());
await shot('23_newgame');
fs.writeFileSync(path.join(out, 'shots-errors.txt'), errors.join('\n\n'));
console.log(errors.length ? 'ERRORS ' + errors.length + ':\n' + errors.slice(0, 8).join('\n---\n') : 'no errors');
await browser.close();
