(() => {
'use strict';
const LD = window.LD;
LD.Content = LD.Content || {};

/* markdown-lite consumed by ui/encyclopedia.js: paragraphs separated by blank lines, "## " headings,
   "- " list items, **bold**, `code`, [[kind:id]] links (item|structure|tech|enemy|layer|guide). */
const md = (...lines) => lines.join('\n');

LD.Content.guides = [
{
  id: 'inicio', title: 'Primeros diez minutos',
  body: md(
    'Empiezas en la superficie ([[layer:0]]) con el [[structure:hub]] (almacén central, 3×3) y las manos vacías. El objetivo de la primera sesión es cerrar el ciclo **recolectar → transformar → investigar**.',
    '',
    '## 1. Mano',
    'Pulsa `H` y haz clic sobre el terreno: bosque alterna [[item:wood_log]] y [[item:stick]] (2), roca da [[item:stone]], pradera [[item:plant_fiber]], arcilla [[item:clay]] y arena [[item:sand]]. Un objeto por clic, con 1,2 s de espera. Las recetas manuales se ejecutan en el propio almacén central: 1 tronco → 4 palos, 1 tronco → 2 tablones y la [[item:hand_tool]] (palo + 2 [[item:flint]] + [[item:rope]]).',
    '',
    '## 2. Mesa de trabajo',
    'La [[structure:workbench]] duplica el rendimiento de las herramientas y fabrica cuerda, marcos y munición. Colócala tocando el almacén o unida a él por cinta.',
    '',
    '## 3. Extracción automática',
    '- [[structure:gather_hut]]: fibra, palos y piedra en radio 4, 0,25/s.',
    '- [[structure:woodcutter]]: tala bosque en radio 5, 0,4 troncos/s; los árboles rebrotan en 900 s.',
    '- [[structure:quarry]]: sobre terreno de roca; 0,6 piedra/s más sílex y grava.',
    '- [[structure:well]]: 0,3 agua/s. El agua es un fluido: necesita un [[structure:tank_wood]] o una tubería, nunca entra en el inventario.',
    '',
    '## 4. Cinta al almacén',
    'Nada produce sin **enlace**: cada máquina debe tocar el almacén central o quedar unida a él por una cadena de [[structure:conveyor_wood]] (2 objetos/s). Arrastra con el ratón para trazar la línea. Ver [[guide:logistica]].',
    '',
    '## 5. Mesa de estudio',
    'La [[structure:study_table]] fabrica [[item:rp0]] (2 palos + 1 sílex + 1 [[item:charcoal]] → 2 unidades, 4 s) y a la vez ejecuta la investigación de la era 0 sin energía. El carbón vegetal sale de la [[structure:charcoal_pit]] (2 troncos → 1). Con la primera tecnología en marcha (`T`) ya estás en el bucle principal: [[guide:investigacion]].'
  ),
  related: ['logistica', 'investigacion', 'naturaleza', 'controles']
},
{
  id: 'inventario_estratos', title: 'Inventario por estrato',
  body: md(
    'Cada uno de los cinco estratos tiene un **inventario independiente**. Las máquinas, extractores y obras de una capa cobran y entregan solo en el inventario de esa capa; la investigación se paga siempre desde la superficie. Los fluidos nunca aparecen en ningún inventario ([[guide:fluidos]]).',
    '',
    '## Capacidad',
    'Cada objeto tiene un tope por capa: 200 unidades base más la suma de `storage.cap` de los almacenes construidos en esa capa ([[structure:warehouse_wood]] +200, [[structure:warehouse_stone]] +600, [[structure:warehouse_steel]] +2500, [[structure:warehouse_auto]] +12 000, [[structure:silo_quantum]] +100 000). Producir por encima del tope bloquea la máquina en `output_full`.',
    '',
    '## Elevadores',
    'Al completar un pozo ([[structure:shaft_coal]], [[structure:shaft_deep]], [[structure:shaft_abyss]], [[structure:shaft_core]]) aparece un [[structure:elevator]] en el centro del nuevo estrato. Mueve objetos entre esa capa y la superficie con un caudal total de 5 objetos/s; los modelos [[structure:elevator_steel]] (20/s), [[structure:elevator_industrial]] (80/s, 100 kW) y [[structure:elevator_quantum]] (400/s, 5 MW) se construyen aparte. El primer elevador de cada estrato no se puede desmantelar.',
    '',
    '## Reglas por elevador',
    '- Regla por defecto `* · subir · 0`: todo lo que haya en la capa sube a la superficie.',
    '- `objeto · bajar · N`: trae desde la superficie hasta que la capa tenga N unidades. Tiene prioridad sobre las subidas y ese objeto nunca sube.',
    '- `objeto · mantener · N`: no sube ese objeto mientras la capa tenga N o menos.',
    '- `objeto · subir · N`: sube solo el excedente por encima de N.',
    'La transferencia respeta el tope de ambas capas y se reduce con la integridad del elevador y del almacén central (≤ 10 % → ×0,1).',
    '',
    '## Construir abajo',
    'Para levantar una tuneladora en [[layer:1]] los materiales deben estar en el inventario de esa capa: añade reglas `bajar` para tablones, ladrillos o placas antes de bajar a construir. Solo se puede edificar en parcelas ya excavadas ([[guide:excavacion]]).'
  ),
  related: ['logistica', 'excavacion', 'construccion', 'fluidos']
},
{
  id: 'logistica', title: 'Logística: cintas y enlaces',
  body: md(
    'Las cintas son abstractas: no transportan objetos visibles, sino que **enlazan** estructuras con el almacén de la capa. Una estructura está enlazada si toca el [[structure:hub]] (superficie) o un elevador (estratos inferiores), o si una cadena de casillas de cinta en 4 vecindad la une a ellos. Sin enlace la máquina marca `no_link` y no trabaja.',
    '',
    '## Caudal',
    'El caudal de una estructura enlazada es el **mayor** de los caudales de las cintas adyacentes a su huella; tocar directamente el almacén o el elevador equivale a caudal infinito. Ese caudal limita la suma de entradas y salidas en objetos por segundo, con una reserva de 5 s de ráfaga:',
    '- [[structure:conveyor_wood]] 2/s',
    '- [[structure:conveyor_iron]] 8/s',
    '- [[structure:conveyor_steel]] 24/s',
    '- [[structure:conveyor_titanium]] 80/s',
    '- [[structure:conveyor_quantum]] 400/s',
    'Una cadena hereda el caudal de sus tramos: una cinta cuántica alimentada por una de madera sigue entregando 2/s. Mezcla tramos de distinto nivel sin problema, pero pon la cinta rápida justo al lado de la máquina que la necesita.',
    '',
    '## Nodos',
    'En los estratos inferiores cualquier elevador actúa como fuente de enlace; en la superficie también lo hacen las cabezas de pozo. Varios elevadores repartidos acortan las cadenas de cinta y suman caudal vertical ([[guide:inventario_estratos]]).',
    '',
    '## Averías',
    'Cintas, cables y tuberías son estructuras: tienen integridad, sufren terremotos y ataques y pueden romperse. Una cinta rota corta el enlace de todo lo que había detrás. Con el almacén central al 10 % de integridad todo su caudal se multiplica por 0,1.',
    '',
    '## Trazado',
    'Arrastra en modo construcción para dibujar líneas rectas; `SHIFT` mantiene el modo tras soltar. Los planos copian cintas junto a cables y tuberías ([[guide:construccion]]).'
  ),
  related: ['inventario_estratos', 'construccion', 'integridad']
},
{
  id: 'energia', title: 'Energía: generadores, cables y redes',
  body: md(
    'La potencia se mide en W, kW, MW y GW. Los consumidores solo demandan mientras trabajan; cada nivel de overclock duplica la demanda ([[guide:overclock]]).',
    '',
    '## Generadores',
    '- [[structure:water_wheel]] 4 kW, junto a agua. [[structure:windmill]] 2,5 kW, ×1,6 con tormenta.',
    '- [[structure:steam_engine]] 60 kW y [[structure:coal_plant]] 400 kW: queman combustible del inventario de la capa y beben agua por tubería.',
    '- [[structure:diesel_generator]] 1,5 MW y [[structure:gas_turbine]] 3 MW: combustible líquido o gas desde la red de tuberías.',
    '- [[structure:solar_panel]] 80 kW de día, ×0,3 con lluvia o tormenta, 0 de noche. [[structure:geothermal_plant]] 5 MW.',
    '- [[structure:fission_reactor]] 150 MW y [[structure:fusion_reactor]] 2 GW ([[guide:nuclear]], [[guide:fusion_nucleo]]).',
    'Un generador de combustible consume `P·dt/1e6` MJ de su depósito interno, recargado con objetos ([[item:coal]] 24 MJ, [[item:coke]] 30, [[item:charcoal]] 16, [[item:wood_log]] 8) o con fluidos. Las fuentes gratuitas se usan antes que las de combustible.',
    '',
    '## Cables y capacidad',
    'Los cables son una capa de casilla: van sobre suelo libre o sobre cintas, nunca bajo otras estructuras. Las estructuras conducen entre sí por contacto. La entrada o salida de potencia de una estructura queda limitada por el **mejor cable adyacente**: [[structure:drive_shaft]] 10 kW, [[structure:cable_copper]] 300 kW, [[structure:cable_hv]] 20 MW, [[structure:cable_super]] sin límite. Dos estructuras que se tocan sin cable comparten 50 kW·2^nivel del más bajo.',
    '',
    '## Redes y apagones',
    'Una red es el componente conexo de cables y estructuras de una capa. Por red: `ratio = min(1, (generación + baterías) / demanda)`; todos los consumidores de la red funcionan a ese ratio. Si baja de 1 se avisa de caída de tensión (una vez cada 30 s por red). Las [[structure:battery]] (50 MJ) y [[structure:capacitor_bank]] (5 GJ) absorben excedente y lo devuelven en picos, limitadas por su cable.',
    '',
    '## Pozos',
    'Un pozo une la red que toca su cabeza en la superficie con la red que toca el elevador del estrato: la superficie puede alimentar las tuneladoras de [[layer:1]] sin generadores abajo.',
    '',
    'La energía producida en cada capa es el principal motor de la amenaza ([[guide:defensa]]).'
  ),
  related: ['overclock', 'fluidos', 'defensa', 'clima_eventos']
},
{
  id: 'fluidos', title: 'Fluidos: tuberías y tanques',
  body: md(
    'Los objetos de categoría fluido o gas ([[item:water]], [[item:crude_oil]], [[item:natural_gas]], ácidos, [[item:hydrogen]]…) **nunca entran en el inventario**. Viven en tanques conectados por tuberías, con redes independientes por capa.',
    '',
    '## Redes',
    'Una red de fluidos es el componente conexo de casillas de tubería y estructuras que manejan fluido (tanques, pozos, bombas, máquinas con entradas o salidas líquidas, pozos de estrato y elevadores). Las tuberías comparten casilla con cables y cintas pero no con otras estructuras. No almacenan nada: sin tanque, la red no retiene fluido.',
    '',
    '## Tanques',
    'Cada tanque contiene **un solo fluido**: [[structure:tank_wood]] 300, [[structure:tank_iron]] 2000, [[structure:tank_steel]] 10 000, [[structure:tank_titanium]] 60 000, [[structure:tank_cryo]] 30 000, [[structure:tank_quantum]] 2 000 000 unidades. Los criogénicos ([[item:liquid_nitrogen]], [[item:deuterium]], [[item:tritium]], [[item:helium3]], [[item:cryo_coolant]], [[item:liquid_hydrogen]]) solo caben en tanques `cryo`, que además consumen energía mientras contienen algo. Una máquina empuja su salida a tanques de ese fluido o vacíos de su red y toma la entrada de tanques del fluido pedido; sin tanque con sitio marca `output_full`, sin fluido `no_fluid`.',
    '',
    '## Caudal',
    'Igual que en las cintas, el caudal de una máquina lo fija la **mejor tubería adyacente**: [[structure:pipe_wood]] 2/s, [[structure:pipe_bronze]] 8/s, [[structure:pipe_steel]] 40/s, [[structure:pipe_titanium]] 200/s, [[structure:pipe_quantum]] sin límite. Tocar un tanque directamente no limita.',
    '',
    '## Pozos, bombas y estratos',
    '[[structure:well]] 0,3 agua/s en cualquier sitio; [[structure:pump_hand]] 1,2/s y [[structure:pump_electric]] 8/s junto a una casilla de agua. La lluvia y la tormenta los multiplican por 1,5. Los pozos de estrato unen las redes de la cabeza y del elevador con el caudal `shaft.rate` del pozo (5, 20, 80 o 400/s).',
    '',
    '## Lubricante',
    'Si la red de una máquina contiene [[item:lubricant]] (mezcladora: 2 [[item:resin]] + 1 [[item:diesel]] → 2), la máquina consume 0,005/s y su desgaste se divide por 1,5 ([[guide:integridad]]).'
  ),
  related: ['energia', 'integridad', 'yacimientos', 'inventario_estratos']
},
{
  id: 'overclock', title: 'Overclock',
  body: md(
    'Cada máquina admite un número de niveles de overclock (`ocMax`, de 0 a 3 según el modelo). Se ajusta desde el panel de selección con `+` y `−`, con previsualización de potencia, velocidad y desgaste.',
    '',
    '## Efecto por nivel',
    '- **Nivel efectivo +1**: la máquina acepta recetas de un nivel superior. Un [[structure:crusher]] T2 con OC 1 ejecuta recetas T3.',
    '- **Potencia ×2**: la demanda mientras trabaja se duplica (OC 2 = ×4, OC 3 = ×8).',
    '- **Velocidad ×1,5**: OC 2 = ×2,25, OC 3 = ×3,375.',
    '- **Desgaste ×3**: OC 2 = ×9, OC 3 = ×27.',
    '',
    '## Velocidad real',
    '`velocidad = base · 1,5^oc · ratio de red · integridad · dificultad`. Con la red al 60 % una máquina con OC 1 rinde 0,9: pagas ×2 de potencia para recibir menos que sin overclock. Comprueba el ratio en la barra superior antes de subir niveles.',
    '',
    '## Desgaste',
    'A plena carga una máquina sin overclock tarda unas 7 h en llegar a 0 %; con OC 1 unas 2 h 20 min, con OC 2 unos 47 min y con OC 3 unos 16 min. El lubricante divide el desgaste por 1,5 y un [[structure:maintenance_bay]] cercano repara en ciclos de 10 s ([[guide:integridad]]).',
    '',
    '## Cuándo usarlo',
    '- Para llegar a una receta de nivel superior sin construir la máquina siguiente.',
    '- Para cuellos de botella puntuales con energía sobrante.',
    '- No para producción sostenida: el coste en energía crece más rápido que la velocidad.',
    'Las torretas y laboratorios también aceptan overclock: ×1,5 de cadencia o de velocidad de investigación por nivel, con la misma demanda ×2. El overclock no cambia el caudal de cintas ni tuberías ([[guide:logistica]]).'
  ),
  related: ['integridad', 'energia', 'logistica']
},
{
  id: 'integridad', title: 'Integridad y desgaste',
  body: md(
    'Cada estructura tiene una reserva de integridad (`hp`). `integridad = hp / hp máximo`. Por debajo del 30 % la máquina pierde eficacia: `multiplicador = max(0,1; 1 − 0,03·(30 − integridad %))`, es decir, 3 % de velocidad por cada punto por debajo del 30 %. A 0 la estructura queda `broken` hasta repararla.',
    '',
    '## Fuentes de pérdida',
    '- **Desgaste por uso**: 0,004 % de `hp` máximo por segundo mientras trabaja (≈ 7 h a plena carga), ×3 por cada nivel de overclock.',
    '- **Calor del núcleo**: en [[layer:4]] toda estructura sin `heatproof` pierde 0,05 %/s de forma continua (unos 33 min hasta 0). Una tormenta de plasma lo triplica durante 90 s.',
    '- **Sobrecalentamiento**: un [[structure:fission_reactor]] sin [[structure:cooling_tower]] adyacente con agua produce la mitad y se desgasta ×5.',
    '- **Tormenta**: los [[structure:windmill]] pierden 0,02 %/s mientras dura.',
    '- **Daño directo**: enemigos y terremotos (3–8 % por sacudida).',
    '',
    '## Reparación',
    'Manual desde el panel: instantánea, cuesta `ceil(coste_i · fracción perdida · 0,5)` de cada material, pagado en el inventario de la capa. El [[structure:maintenance_bay]] (40 kW) repara cada 10 s hasta cinco estructuras cuya huella esté a 8 casillas o menos de la suya, empezando por las más dañadas, solo si están por debajo del 90 % o rotas y si la capa tiene los materiales.',
    '',
    '## Lubricante',
    'Con [[item:lubricant]] en la red de tuberías de la máquina el desgaste se divide por 1,5 a cambio de 0,005 unidades/s ([[guide:fluidos]]).',
    '',
    '## Almacén central',
    'El [[structure:hub]] es indestructible: nunca baja del 10 %. Al 10 % o menos todo su caudal (enlaces, entrada de elevadores) se multiplica por 0,1, así que repáralo tras cada oleada ([[guide:defensa]]).'
  ),
  related: ['overclock', 'fluidos', 'defensa', 'construccion']
},
{
  id: 'construccion', title: 'Construcción, desmontaje y planos',
  body: md(
    '`B` abre la paleta por categorías; los elementos bloqueados muestran la tecnología que los desbloquea y la lista de coste se colorea según el inventario de la capa actual. Colocar paga el **coste completo** de inmediato desde esa capa.',
    '',
    '## Tiempos',
    'Cada estructura tiene `buildTime` entre 1 s (cintas, cables, tuberías) y 60 s ([[structure:fusion_reactor]]), multiplicado por la dificultad (Pacífico ×0,8, Normal ×1, Brutal ×1,3). Durante la obra el estado es `building`; no produce ni conduce.',
    '',
    '## Desmontaje',
    'Modo `X` o botón del panel: mientras está en obra devuelve el **100 %**; una vez terminada, `floor(0,65 · coste_i)` por material (65 %). El reembolso va al inventario de la capa y lo que no quepa por tope se pierde: el panel muestra la previsión. El [[structure:hub]] y el primer elevador de cada estrato no se pueden desmantelar.',
    '',
    '## Orientación',
    '`R` rota mientras colocas (4 orientaciones). Es puramente estética: enlaces, redes y rangos no dependen de la rotación.',
    '',
    '## Rangos y terreno',
    'Al colocar se muestran radios de torretas, taller, leñador, etc. (ajuste «rangos siempre»). Algunas estructuras exigen terreno: la [[structure:quarry]] roca, el [[structure:clay_pit]] arcilla, el [[structure:water_wheel]] contacto con agua; los extractores deben cubrir un yacimiento ([[guide:yacimientos]]). En los estratos inferiores solo se construye sobre parcelas excavadas.',
    '',
    '## Planos y cola',
    '`C` copia una selección rectangular con estructuras, cintas, cables y tuberías; `V` pega el último plano y `R` lo rota. Cada celda que se puede pagar se coloca al instante; el resto entra en una **cola** que intenta una colocación cada 0,5 s, en orden, reservando sus casillas para que nadie construya encima. Las celdas de estructuras aún no investigadas se descartan. La lista de planos permite renombrar, borrar y ver el coste total.',
    '',
    'Cintas, cables y tuberías se trazan arrastrando; `SHIFT` mantiene el modo de colocación al soltar ([[guide:controles]]).'
  ),
  related: ['logistica', 'integridad', 'controles', 'inventario_estratos']
},
{
  id: 'excavacion', title: 'Excavación de estratos',
  body: md(
    'La superficie es edificable por completo. Los estratos [[layer:1]] a [[layer:4]] nacen como roca maciza dividida en **parcelas de 16×16** casillas; solo el chunk del elevador y sus cuatro vecinos ortogonales empiezan excavados.',
    '',
    '## Dureza',
    'La dureza de una parcela crece con su distancia Chebyshev `d` (en parcelas) al centro: `H = rockBase · (1 + rockPerChunk · d)` y el trabajo necesario es `H · 256`. Valores por estrato:',
    '- [[layer:1]]: base 1, +35 % por parcela.',
    '- [[layer:2]]: base 2, +40 %.',
    '- [[layer:3]]: base 4, +45 %.',
    '- [[layer:4]]: base 7, +50 %.',
    'La dureza se muestra al pasar el ratón sobre la roca rayada; una parcela en obra dibuja un anillo de progreso.',
    '',
    '## Tuneladoras',
    'Una tuneladora excava si su huella toca el borde de una parcela **sin excavar** que a su vez toca una excavada. Su nivel efectivo debe alcanzar el `borerTier` del estrato (2, 3, 5 y 7): [[structure:borer_steam]] 2 casillas/s (carbón y agua), [[structure:borer_electric]] 4/s (80 kW), [[structure:borer_laser]] 10/s (2 MW), [[structure:borer_plasma]] 30/s (60 MW). Cada nivel por encima del exigido duplica el ritmo, y el overclock cuenta como nivel. Ejemplo: parcela a `d = 3` en [[layer:2]]: `H = 2·(1+1,2) = 4,4`, trabajo 1126; una tuneladora eléctrica en el nivel justo tarda 282 s.',
    '',
    '## Rendimientos',
    'Mientras excava y está enlazada entrega al inventario de la capa [[item:stone]] 0,3/s, [[item:gravel]] 0,2/s y la mena común del estrato a 0,05/s. Al terminar, la parcela genera suelo, pilares y yacimientos (los cercanos al centro siempre incluyen las menas básicas), se emite `chunk:excavated` y la máquina queda `idle` hasta que se asigne otra parcela. Desde el panel se elige el objetivo.',
    '',
    'El anillo exterior es el más duro y también el único con yacimientos infinitos ([[guide:yacimientos]]).'
  ),
  related: ['yacimientos', 'inventario_estratos', 'energia']
},
{
  id: 'yacimientos', title: 'Yacimientos y extractores',
  body: md(
    'Los yacimientos son una capa sobre el terreno edificable. Los de las parcelas centrales son **finitos** y se agotan (la casilla vuelve a suelo liso); los del **anillo exterior** son infinitos: el borde y las esquinas de la superficie y, en los estratos inferiores, las parcelas más lejanas y duras (`d ≥ maxD − 1`). El final de partida siempre es alcanzable.',
    '',
    '## Dureza de mena',
    'Cada yacimiento tiene una dureza 0–7. Un extractor solo trabaja sobre casillas con `dureza ≤ hardnessMax` y su ritmo es `rate · casillas cubiertas · velocidad`:',
    '- [[structure:mine_hand]] h0, 0,25/s · [[structure:mine_gallery]] h1, 0,4/s',
    '- [[structure:drill_steam]] h2, 0,8/s · [[structure:drill_electric]] h3, 1,5/s · [[structure:excavator]] h4, 2,5/s',
    '- [[structure:drill_laser]] h5, 5/s · [[structure:drill_cryo]] h6, 9/s (bebe [[item:liquid_nitrogen]]) · [[structure:extractor_plasma]] h7, 20/s',
    'El overclock no eleva `hardnessMax`. Un taladro 2×2 sobre cuatro casillas de yacimiento rinde el cuádruple que sobre una.',
    '',
    '## Por estrato',
    '- [[layer:0]]: cobre, estaño, hierro y carbón (h0).',
    '- [[layer:1]]: carbón, hierro, caliza, azufre, salitre, sal, sílex (h1); [[item:crude_oil]] (h2).',
    '- [[layer:2]]: zinc, plomo, níquel, bauxita, cuarzo (h2); cromita, manganeso, plata, oro, amatista (h3); [[item:natural_gas]] (h3).',
    '- [[layer:3]]: rutilo, wolframita, cobalto, espodumena, molibdenita, fluorita, basalto, obsidiana (h4); uraninita, monacita, vanadinita, torita, platino, gemas (h5).',
    '- [[layer:4]]: [[item:corestone]], iridio, osmio, [[item:plasma_crystal]] (h6); [[item:neutronium_ore]] (h7); [[item:magma]], [[item:deuterium_brine]] (h6) y [[item:helium3]] (h7).',
    '',
    '## Fluidos',
    'Los yacimientos líquidos requieren extractores con `extract.fluid`: [[structure:pumpjack]] (crudo), [[structure:gas_well]] (gas), [[structure:brine_pump]] (salmuera y magma), [[structure:he3_collector]]. Su salida va a la red de tuberías y no necesita enlace por cinta ([[guide:fluidos]]).',
    '',
    'Los terremotos y el evento «nueva veta» pueden revelar yacimientos finitos nuevos ([[guide:clima_eventos]]).'
  ),
  related: ['excavacion', 'procesado_menas', 'fluidos', 'clima_eventos']
},
{
  id: 'investigacion', title: 'Investigación',
  body: md(
    'Unas cien tecnologías en ocho eras (Edad de piedra → Era cuántica). Cada tecnología desbloquea estructuras y recetas; todo lo que no está disponible al inicio lo desbloquea exactamente una tecnología, y la paleta indica cuál.',
    '',
    '## Paquetes de ciencia',
    'Los costes se pagan en objetos de ciencia **desde el inventario de la superficie** al iniciar la tecnología:',
    '- [[item:rp0]] Saber primitivo: 2 [[item:stick]] + 1 [[item:flint]] + 1 [[item:charcoal]] → 2 en la [[structure:study_table]].',
    '- [[item:rp1]] Ciencia básica: hilo de cobre, engranaje de bronce y tela.',
    '- [[item:rp2]] Ciencia industrial: placa de acero, circuito básico y vidrio.',
    '- [[item:rp3]] Ciencia química: plástico, ácido sulfúrico, circuito avanzado y celda.',
    '- [[item:rp4]] Ciencia nuclear: pastilla de uranio, procesador y refrigerante.',
    '- [[item:rp5]] Ciencia cuántica: procesador cuántico, celda de plasma y neutronio.',
    'Las recetas de ciencia se ejecutan en los propios laboratorios (tipo `research`).',
    '',
    '## Laboratorios y tiempo',
    'Cada tecnología exige un laboratorio de nivel mínimo: 0 [[structure:study_table]] (sin energía), 1 [[structure:lab_basic]] (10 kW), 2 [[structure:lab_industrial]] (200 kW), 3 [[structure:lab_quantum]] (5 MW). Cada laboratorio suficiente, enlazado y alimentado resta `1 · ratio de red · 1,5^oc · integridad` segundos por segundo del contador `time`: dos laboratorios investigan el doble de rápido (lineal). Los laboratorios muestran `working` mientras hay una tecnología activa.',
    '',
    '## Cola',
    'Desde el árbol (`T`) se encola cualquier tecnología: sus requisitos pendientes entran antes. Al terminar una, la siguiente de la cola arranca si la superficie puede pagarla; si no, se reintenta cada segundo y las entradas cuyos requisitos ya no pueden cumplirse se descartan. Al completar una tecnología se descubren sus desbloqueos en la enciclopedia y, si procede, avanza la era.',
    '',
    '## Siguiente paso',
    'La sección Tecnologías lista hasta seis tecnologías alcanzables ordenadas por era y coste, con los paquetes que faltan en superficie. Úsala para decidir qué producir antes que qué investigar. Objetivo de ritmo: era 1 a los 10 min, era 2 a los 40, era 7 (fusión) hacia las 30 h.'
  ),
  related: ['inicio', 'energia', 'inventario_estratos']
},
{
  id: 'defensa', title: 'Defensa: amenaza y oleadas',
  body: md(
    '## Amenaza',
    'Cada estrato desbloqueado con al menos una estructura acumula amenaza por minuto: `0,3 + 1,2·log10(1 + energía/1000) + 0,01·estructuras`, donde `energía` es la media de vatios generados en la capa. La **energía manejada** es el motor principal: una red de 1 MW suma casi cuatro veces más que el tiempo por sí solo. La barra superior muestra amenaza y cuenta atrás.',
    '',
    '## Oleadas',
    'Intervalo base 720 s en [[layer:0]], 780, 840, 900 y 960 s en las capas siguientes, ×dificultad (Fácil ×1,5, Difícil ×0,75) y ±20 % aleatorio: entre 10 y 15 min en Normal. Tamaño `2 + floor(amenaza/6)`; de noche en la superficie ×1,5. Cada quinta oleada trae jefe (uno más por cada 30 de amenaza). Aviso 60 s antes. Aparecen en el borde del mapa (superficie) o en grietas, escombros y bordes de lo excavado (abajo). Las migraciones son oleadas ×2,5 ([[guide:clima_eventos]]).',
    '',
    '## Trayectoria y brechas',
    'Los enemigos calculan A* hasta el [[structure:hub]] o el elevador rodeando muros, estructuras y agua, y recalculan al cambiar la base (máx. una vez cada 2 s). Si no hay camino, apuntan a la estructura más débil sobre la recta hacia el objetivo, prefiriendo muros, y abren **brecha**. Atacan cualquier estructura a 0,8 casillas de su ruta cuando algo los bloquea. Las estructuras rotas se vuelven transitables.',
    '',
    '## Muros',
    '[[structure:palisade]] 150, [[structure:stone_wall]] 500, [[structure:steel_wall]] 2000, [[structure:titanium_wall]] 6000, [[structure:thermal_wall]] 20 000 de integridad. Un anillo completo obliga a la brecha por el punto más débil: refuerza uniformemente.',
    '',
    '## Daño y armadura',
    'Sin perforación: `daño = max(0,1·daño, daño − armadura)`, luego por tipo: cinético ×0,5 cristal, ×0,4 basalto, 0 vacío; térmico ×1,4 quitina, ×0,6 basalto; eléctrico ×1,5 cristal, ×0,8 quitina; plasma ×1 contra todo. La armadura **vacío** ([[enemy:void_wraith]], [[enemy:core_guardian]]) solo cae ante perforación térmica o de plasma: en [[layer:4]] sirve el [[structure:plasma_turret]].',
    '',
    '## Torretas y munición',
    '[[structure:watchtower]], [[structure:ballista]], [[structure:cannon_turret]] y [[structure:gatling_turret]] gastan [[item:arrow]], [[item:ballista_bolt]], [[item:cannon_shell]] y [[item:bullet]] del inventario de la capa; [[structure:tesla_coil]], [[structure:laser_turret]] y [[structure:plasma_turret]] solo energía. La niebla resta 1 al alcance. El [[structure:hub]] nunca baja del 10 %, pero a ese nivel su caudal es ×0,1 ([[guide:integridad]]).'
  ),
  related: ['energia', 'integridad', 'clima_eventos', 'construccion']
},
{
  id: 'clima_eventos', title: 'Clima, ciclo diario y eventos',
  body: md(
    '## Día y noche',
    'El día dura 600 s. La fracción 0,55–1 es noche: luz ambiente 0,35 en la superficie, [[structure:solar_panel]] a 0 y oleadas de [[layer:0]] ×1,5 de tamaño. Los estratos inferiores tienen oscuridad real permanente: [[structure:torch]] y [[structure:lamp]] (50 W) iluminan, igual que máquinas activas, cristales y magma.',
    '',
    '## Meteorología (solo superficie)',
    'Probabilidad por periodo: despejado 55 %, niebla 15 %, lluvia 20 %, tormenta 10 %; cada episodio dura 3–8 min y se anuncia 30 s antes.',
    '- **Lluvia**: [[structure:well]] y bombas ×1,5; solar ×0,3.',
    '- **Tormenta**: [[structure:windmill]] ×1,6 con desgaste 0,02 %/s; solar ×0,3; bombas ×1,5.',
    '- **Niebla**: ambiente ×0,8; alcance de torretas −1.',
    '',
    '## Eventos especiales',
    'Uno cada 12–25 min, anunciado 60 s antes (10 min de gracia al empezar):',
    '- **Terremoto** ([[layer:1]]–[[layer:4]]): entre el 20 y el 40 % de las estructuras de la capa pierden 3–8 % de integridad, aparecen escombros y hay un 40 % de probabilidad de que se exponga una veta.',
    '- **Tormenta de plasma** ([[layer:4]]): pérdida por calor del núcleo ×3 durante 90 s. Aloja las máquinas críticas en estructuras `heatproof` y ten un [[structure:maintenance_bay]] cerca.',
    '- **Migración** ([[layer:0]]): oleada ×2,5 fuera del calendario; cuenta como oleada normal para el jefe.',
    '- **Nueva veta**: un yacimiento finito aparece en una parcela excavada de un estrato desbloqueado al azar.',
    '',
    '## Preparación',
    'El registro y los avisos de la barra superior listan cada anuncio con su cuenta atrás. Con niebla, acerca las torretas al perímetro; con tormenta, la energía eólica sobra y la solar falta: las [[structure:battery]] nivelan ([[guide:energia]]). Tras un terremoto repasa cintas y tuberías rotas ([[guide:logistica]]).'
  ),
  related: ['defensa', 'energia', 'integridad', 'naturaleza']
},
{
  id: 'naturaleza', title: 'Naturaleza: bosque, cultivos y agua',
  body: md(
    '## Árboles',
    'El bosque de la superficie es la fuente de [[item:wood_log]], [[item:stick]] y [[item:resin]]. Cada casilla de bosque tiene un crecimiento 0–1: se tala a partir de 0,6 (3 troncos, 5 % de resina) y rebrota a razón de 1/900 por segundo (15 min de tocón a árbol). Además, la pradera junto al bosque se siembra sola muy despacio (1/1800 s por muestra). El [[structure:woodcutter]] tala en radio 5 el árbol más maduro a 0,4 troncos/s; con más leñadores de los que el bosque regenera, la zona se agota y toca esperar.',
    '',
    '## Vivero y plantación',
    'El [[structure:planter]] planta en radio 5 una casilla de pradera libre, prefiriendo las que tocan bosque, cada 20 s con 0,05 agua/s; si hay [[item:sapling]] en la superficie lo gasta y el ciclo es un 30 % más rápido. Combinado con dos leñadores forma un bosque sostenible.',
    '',
    '## Granjas',
    'Funcionan como máquinas de salida fija que beben agua por tubería y necesitan enlace:',
    '- [[structure:tree_farm]] 0,5 troncos/s (0,1 agua/s).',
    '- [[structure:fiber_farm]] 0,4 [[item:plant_fiber]]/s.',
    '- [[structure:bonsai]] 0,15 troncos/s con 200 W, construible **en cualquier estrato**; [[structure:bonsai_hydro]] 0,6 troncos + 0,06 resina/s con 2 kW.',
    '- [[structure:algae_farm]] 0,8 [[item:algae]]/s (biocombustible) y [[structure:greenhouse]]: fibra, [[item:rubber_sap]] y plantones.',
    '- [[structure:hunting_lodge]]: [[item:hide]], [[item:bone]] y [[item:sinew]] según la fauna salvaje del radio 6.',
    '- Extractores de terreno: [[structure:quarry]] (roca), [[structure:clay_pit]], [[structure:sand_pit]], [[structure:peat_cutter]] (turbera) y [[structure:salt_works]] (salinas, consume agua).',
    'Todas admiten overclock ([[guide:overclock]]).',
    '',
    '## Agua',
    'El [[structure:well]] da 0,3/s en cualquier lugar; [[structure:pump_hand]] (1,2/s) y [[structure:pump_electric]] (8/s, 6 kW) deben tocar agua. La lluvia multiplica los tres por 1,5. El agua es un fluido: cada consumidor necesita tubería o contacto directo con un tanque ([[guide:fluidos]]). Las granjas de los estratos inferiores necesitan su propia red o un pozo de estrato que la traiga desde arriba.',
    '',
    'Recolección manual: `H`, 1 objeto cada 1,2 s, solo en la superficie ([[guide:inicio]]).'
  ),
  related: ['inicio', 'fluidos', 'clima_eventos', 'yacimientos']
},
{
  id: 'procesado_menas', title: 'Procesado de menas y aleaciones',
  body: md(
    'La fundición directa (1 mena → 1 lingote) funciona desde el primer minuto, pero desperdicia la mitad del yacimiento. La cadena completa es **triturar → lavar → fundir**.',
    '',
    '## Triturar (×2)',
    'La [[structure:millstone]] (T1, 2 kW) convierte 2 menas en 3 trituradas; el [[structure:crusher]] (T2, 15 kW) convierte **1 mena en 2 trituradas** en 5 s. Cada mena triturada funde en un lingote, así que el yacimiento rinde el doble. Cubre las 23 menas, incluidas [[item:uraninite]] y [[item:neutronium_ore]] (12 s).',
    '',
    '## Lavado y subproductos',
    'En la [[structure:mixer]] (tipo lavado, T2) 2 trituradas + 2 [[item:water]] → 2 purificadas más trazas de otras menas en 6 s:',
    '- cobre → 0,1 oro triturado; plata → 0,1 oro; oro → 0,2 plata.',
    '- estaño → 0,15 zinc; hierro → 0,15 manganeso; plomo → 0,15 plata.',
    '- zinc → 0,15 plomo + 0,05 plata; níquel → 0,1 cobalto + 0,03 platino; platino → 0,05 iridio + 0,05 osmio.',
    'Las fracciones se acumulan y se entregan por unidades enteras. La purificada funde algo más rápido (4 s) y el agua exige tubería ([[guide:fluidos]]). El lavado es la única fuente temprana de manganeso, cobalto y platino.',
    '',
    '## Aleaciones principales',
    '- [[item:bronze_ingot]]: 3 cobre + 1 estaño → 4 (T1, [[structure:bronze_forge]]); también directo desde trituradas 3:1.',
    '- [[item:brass_ingot]]: 3 cobre + 1 zinc → 4. [[item:electrum_ingot]]: oro + plata → 2.',
    '- [[item:steel_ingot]]: 2 hierro + 1 [[item:coke]] → 2 en el [[structure:blast_furnace]]; con manganeso 4 hierro + 2 coque + 1 manganeso → 5; en el [[structure:arc_furnace]] 4 hierro + coque + electrodo → 4 en 10 s.',
    '- [[item:stainless_ingot]]: 6 acero + 2 cromo + 1 níquel → 8 (horno eléctrico) o → 9 (arco).',
    '- [[item:tungsten_carbide]]: wolframio + grafito en el [[structure:vacuum_furnace]].',
    '- [[item:superalloy_ingot]]: 4 níquel + 2 cromo + 1 cobalto + 1 molibdeno → 6 (vacío, 24 s).',
    '- [[item:core_alloy]]: 2 [[item:corestone]] + iridio + carburo → 2 ([[guide:fusion_nucleo]]).',
    'El [[item:coke]] sale del [[structure:coke_oven]] (2 carbón → 1 coque + 1 [[item:tar]]); el alquitrán es fluido. Asigna la receta por máquina o usa «aplicar a todas» para cada tipo en la capa.'
  ),
  related: ['yacimientos', 'fluidos', 'nuclear', 'fusion_nucleo']
},
{
  id: 'nuclear', title: 'Ciclo del combustible nuclear',
  body: md(
    'La era nuclear (T6) exige una cadena química larga. Todo el procesado húmedo son fluidos en tuberías; solo los sólidos pasan por el inventario.',
    '',
    '## De la mena a la barra',
    '- [[item:uraninite]] (h5, [[layer:3]]) → [[structure:crusher]] → 2 [[item:crushed_uraninite]].',
    '- [[structure:chemical_plant]]: 4 uraninita triturada + 4 [[item:sulfuric_acid]] → 2 [[item:yellowcake]] (12 s).',
    '- [[structure:chemical_plant]]: 1 yellowcake + 4 [[item:hydrofluoric_acid]] → 4 [[item:uf6]] (gas).',
    '- [[structure:enrichment_centrifuge]] (2 MW): 8 UF6 → 1 [[item:enriched_uf6]] + 6 [[item:depleted_uf6]] (30 s). Cada barra necesita 64 UF6.',
    '- [[structure:fuel_fabricator]]: 2 UF6 enriquecido + [[item:hydrogen]] + agua → 2 [[item:uranium_pellet]] (devuelve 2 HF, que conviene recircular).',
    '- 8 pastillas + 2 [[item:stainless_plate]] → 1 [[item:fuel_rod]] (400 000 MJ).',
    '',
    '## Reactor',
    'El [[structure:fission_reactor]] (3×3) produce 150 MW quemando [[item:fuel_rod]], [[item:mox_rod]] o [[item:thorium_fuel]]; consume 5 agua/s y **exige una [[structure:cooling_tower]] adyacente** con 2 agua/s. Sin torre, la potencia se reduce a la mitad y el desgaste se multiplica por 5. Cada barra deja 1 [[item:spent_fuel]] en el inventario. A plena carga una barra dura 2667 s (44 min). Usa [[structure:cable_hv]] (20 MW) en paralelo o [[structure:cable_super]] para evacuar la potencia; el hilo de cobre satura a 300 kW ([[guide:energia]]).',
    '',
    '## Residuos y MOX',
    '- [[item:depleted_uf6]] + hidrógeno → [[item:depleted_uranium]] (fabricador, 4:1).',
    '- 2 [[item:spent_fuel]] + 4 [[item:nitric_acid]] → 1 [[item:plutonium]] + 2 uranio empobrecido.',
    '- 1 plutonio + 7 uranio empobrecido + 2 placas → [[item:mox_rod]] (500 000 MJ): cierra el ciclo y aprovecha el 6/8 de uranio que descarta el enriquecimiento.',
    '',
    '## Torio',
    '[[item:thorite]] (h5) → triturada → [[structure:arc_furnace]]: 2 torita + 2 [[item:hydrochloric_acid]] → [[item:thorium_ingot]] (24 s). 6 torio + 2 pastillas de uranio + 2 placas → [[item:thorium_fuel]] (300 000 MJ): menos energía por barra, pero solo dos pastillas enriquecidas por cada seis lingotes.',
    '',
    'La [[item:rp4]] necesita pastillas de uranio: monta la cadena antes de investigar la era nuclear a fondo. La energía generada dispara la amenaza ([[guide:defensa]]).'
  ),
  related: ['energia', 'procesado_menas', 'fluidos', 'fusion_nucleo']
},
{
  id: 'fusion_nucleo', title: 'Fusión y materiales del núcleo',
  body: md(
    '[[layer:4]] es el último estrato: tuneladoras T7, calor continuo (0,05 %/s en toda estructura sin `heatproof`), tormentas de plasma y enemigos con armadura de vacío. Aquí se cierra el juego: 2 GW de fusión y [[item:neutronium_ingot]].',
    '',
    '## Combustibles',
    '- [[item:deuterium]]: [[structure:brine_pump]] extrae [[item:deuterium_brine]] (h6) por tubería; la [[structure:centrifuge]] concentra 20 → 1 en 20 s y la [[structure:cryo_plant]] 10 → 1 en 16 s. Es criogénico: solo [[structure:tank_cryo]] o [[structure:tank_quantum]].',
    '- [[item:tritium]]: [[structure:fuel_fabricator]], 2 [[item:lithium_ingot]] + 1 deuterio → 1 (30 s). El litio viene de la [[item:spodumene]] de [[layer:3]].',
    '- [[item:helium3]]: [[structure:he3_collector]] (h7, 20 MW) sobre chimeneas del núcleo, 1/s por casilla.',
    '',
    '## Pastillas y reactor',
    'En la [[structure:cryo_plant]]: 2 deuterio + 2 tritio → [[item:fusion_pellet]] (6 000 000 MJ, 30 s); 3 helio-3 + 1 deuterio → [[item:he3_pellet]] (9 000 000 MJ). El [[structure:fusion_reactor]] (3×3, 60 s de obra, `heatproof`) genera **2 GW** sin agua ni torre: una pastilla D-T dura 50 min a plena carga. Solo [[structure:cable_super]] transporta esa potencia; distribuye con varias redes o estará limitado por el cable adyacente ([[guide:energia]]).',
    '',
    '## Materiales del núcleo',
    '- [[item:core_alloy]]: 2 [[item:corestone]] + 1 [[item:iridium_ingot]] + 1 [[item:tungsten_carbide]] → 2 en la [[structure:nano_forge]] (40 s).',
    '- [[item:core_frame]]: 4 aleación + 2 [[item:thermal_plate]] + 2 [[item:nanotube]]. Estructura de todas las máquinas T7.',
    '- [[item:plasma_cell]]: [[item:plasma_crystal]] + 2 [[item:liquid_hydrogen]] → 1; con [[item:void_essence]] (botín de [[enemy:void_wraith]]) → 2.',
    '- [[item:containment_coil]] y [[item:plasma_injector]]: bobinas superconductoras y ósmio, platino, lentes y procesadores; se ensamblan en la nanoforja.',
    '',
    '## Neutronio',
    '[[item:neutronium_ore]] (h7) solo cede ante el [[structure:extractor_plasma]] (40 MW). 4 [[item:crushed_neutronium]] + 1 celda de plasma → 1 [[item:neutronium_ingot]] (60 s), o con 2 esencia del vacío en 50 s. Con él se fabrica [[item:rp5]] y el equipo cuántico final ([[structure:matter_assembler]], [[structure:elevator_quantum]], [[structure:silo_quantum]]).',
    '',
    'Aísla el estrato con [[structure:thermal_wall]] (20 000) y [[structure:plasma_turret]]: ninguna otra torreta daña la armadura de vacío ([[guide:defensa]]).'
  ),
  related: ['nuclear', 'energia', 'defensa', 'excavacion']
},
{
  id: 'controles', title: 'Controles y modos',
  body: md(
    'Todas las teclas actúan sobre el mundo salvo cuando un campo de texto tiene el foco. `ESC` cierra primero la ventana superior, luego cancela el modo activo y por último abre la pausa.',
    '',
    '## Cámara y capas',
    '- `W A S D` o flechas: desplazar. `SHIFT` duplica la velocidad. Botón central: arrastrar.',
    '- Rueda: zoom 0,5×–3× centrado en el cursor.',
    '- `1`–`5`: cambiar de estrato (también el widget de estratos del HUD). Cada capa recuerda su cámara.',
    '',
    '## Construcción',
    '- `B`: paleta de construcción. Clic coloca; arrastrar traza cintas, cables y tuberías. `SHIFT` mantiene la pieza tras colocar. Clic derecho o `ESC` cancela.',
    '- `R`: rotar la pieza o el plano al colocar. Fuera de ese modo abre el árbol tecnológico.',
    '- `X`: modo desmontar (reembolso 65 %, 100 % en obra). `SUPR` desmonta la estructura seleccionada.',
    '- `C`: seleccionar rectángulo y guardar plano. `V`: pegar el último plano.',
    '- `H`: recolectar a mano en la superficie (1 objeto / 1,2 s).',
    '',
    '## Información',
    '- `E`: enciclopedia. Dentro: `/` o `F` busca, flechas cambian de entrada, `E` o `ESC` cierra.',
    '- `T`: árbol tecnológico con cola y «Siguiente paso».',
    '- `G`: estadísticas de producción y energía (10 o 60 min, por estrato).',
    '- `F3`: contador de FPS. Clic en una estructura: panel de selección con receta, overclock, integridad, reglas de elevador, tanque, objetivo de tuneladora y munición.',
    '',
    '## Simulación y guardado',
    '- `ESPACIO`: pausa la simulación sin cerrar el mundo.',
    '- `CTRL+S`: guardado rápido en la ranura automática. El autoguardado también salta al ocultar la pestaña.',
    '- No hay progreso sin conexión: al cargar solo se informa del tiempo transcurrido.',
    '',
    '## Modos del cursor',
    'La barra inferior indica el modo activo (COLOCAR, DESMONTAR, RECOLECTAR, COPIAR PLANO, PEGAR) con sus teclas. En modo normal el clic selecciona; con «rangos siempre» activo en ajustes se dibujan los radios de todas las estructuras seleccionadas o al colocar ([[guide:construccion]]).'
  ),
  related: ['inicio', 'construccion', 'investigacion']
}
];
})();
