(() => {
'use strict';
const LD = window.LD;
LD.Content = LD.Content || {};
const shade = (hex, k) => { const n = parseInt(hex.slice(1), 16); const c = v => Math.round(Math.max(0, Math.min(255, v * k))).toString(16).padStart(2, '0'); return '#' + c((n >> 16) & 255) + c((n >> 8) & 255) + c(n & 255); };
const items = [];
/* I(id, name, cat, tier, color, desc, extra?) — color2 defaults to a darker shade of color */
const I = (id, name, cat, tier, color, desc, o) => { items.push(Object.assign({ id, name, cat, tier, color, color2: shade(color, 0.62), desc, fuel: 0, final: false }, o || {})); };

/* ── raw: surface ── */
I('wood_log', 'Tronco', 'organic', 0, '#8a6a48', 'Tronco verde de talar el bosque. Se asierra en tablones o se carboniza en la carbonera.', { fuel: 8 });
I('stick', 'Vara', 'organic', 0, '#a08054', 'Rama recta y seca. Mango de herramientas, astil de flechas y leña de arranque.', { fuel: 1 });
I('plant_fiber', 'Fibra vegetal', 'organic', 0, '#7f8f5a', 'Fibra bast de hierbas y cortezas. Se tuerce en cuerda y se teje en tela.');
I('stone', 'Piedra', 'raw', 0, '#8a8478', 'Bloque irregular de roca. Material de construcción primario y carga para el mortero.');
I('gravel', 'Grava', 'raw', 0, '#9a9488', 'Roca fragmentada de cantera y excavación. Árido para hormigón y lecho de cimentación.');
I('flint', 'Sílex', 'raw', 0, '#5a5854', 'Nódulo de sílice criptocristalina. Rompe en filos cortantes y produce chispa contra el hierro.');
I('clay', 'Arcilla', 'raw', 0, '#a8785a', 'Silicato plástico extraído de la barrera. Cocido da ladrillo y cerámica.');
I('sand', 'Arena', 'raw', 0, '#c9b98a', 'Arena silícea de grano fino. Fundente y materia prima del vidrio y el silicio.');
I('water', 'Agua', 'fluid', 0, '#5a86a8', 'Agua dulce de pozo o bomba. Refrigerante, disolvente y vapor para las máquinas.');
I('hide', 'Piel', 'organic', 0, '#9a7a5c', 'Piel cruda de caza. Curtida se convierte en cuero.');
I('bone', 'Hueso', 'organic', 0, '#d8d0b8', 'Hueso de animal. Molido es harina fosfatada; entero, mango y herramienta.');
I('sinew', 'Tendón', 'organic', 0, '#c0a888', 'Tendón seco y fibroso. Cordaje elástico para arcos y ligaduras.');
I('resin', 'Resina', 'organic', 0, '#c89a4a', 'Exudado de coníferas recogido al talar. Adhesivo, sellante y aislante primitivo.');
I('sapling', 'Plantón', 'organic', 1, '#6f8f4a', 'Árbol joven de vivero listo para trasplante. Repuebla el bosque talado.');
I('copper_ore', 'Mena de cobre', 'ore', 0, '#9c7a5a', 'Malaquita y calcopirita superficiales. Se tritura antes de fundir.');
I('tin_ore', 'Mena de estaño', 'ore', 0, '#8f8c86', 'Casiterita en placeres someros. Con el cobre forma bronce.');
I('iron_ore', 'Mena de hierro', 'ore', 1, '#8c6a56', 'Hematites y magnetita. Reducida en horno da hierro; con coque, acero.');
I('peat', 'Turba', 'fuel', 1, '#5a4a38', 'Materia vegetal semicarbonizada de la turbera. Combustible pobre pero abundante.', { fuel: 10 });
I('salt', 'Sal', 'raw', 1, '#dcdad2', 'Cloruro sódico de salinas. Fuente de cloro y salmuera refrigerante.');
/* ── raw: L1 ── */
I('coal', 'Carbón', 'fuel', 2, '#2e2c2a', 'Hulla de las vetas someras. Combustible industrial y precursor del coque.', { fuel: 24 });
I('limestone', 'Caliza', 'raw', 2, '#c8c2b0', 'Carbonato cálcico sedimentario. Calcinado da cal viva; fundente en el alto horno.');
I('sulfur', 'Azufre', 'raw', 2, '#d9c94a', 'Azufre nativo de fumarolas fósiles. Base de la pólvora y del ácido sulfúrico.');
I('saltpeter', 'Salitre', 'raw', 2, '#d8d8c8', 'Nitrato potásico de eflorescencias. Oxidante de la pólvora y fuente de nitratos.');
I('crude_oil', 'Petróleo crudo', 'fluid', 3, '#2a2622', 'Hidrocarburo bruto extraído con balancín. Se fracciona en nafta, diésel, queroseno y lubricante.');
/* ── raw: L2 ── */
I('zinc_ore', 'Mena de zinc', 'ore', 3, '#8a8f96', 'Esfalerita de las profundidades. Aleado con cobre produce latón.');
I('lead_ore', 'Mena de plomo', 'ore', 3, '#6e6c74', 'Galena densa y brillante. Plomo para blindaje, soldadura y acumuladores.');
I('silver_ore', 'Mena de plata', 'ore', 3, '#b4b4b8', 'Argentita asociada a la galena. Plata para contactos y barras de control.');
I('gold_ore', 'Mena de oro', 'ore', 3, '#b39a4c', 'Cuarzo aurífero. Oro para hilo de contactos de alta fiabilidad.');
I('nickel_ore', 'Mena de níquel', 'ore', 3, '#8f9080', 'Pentlandita. Níquel para aceros inoxidables y superaleaciones.');
I('quartz', 'Cuarzo', 'crystal', 3, '#d8d4cc', 'Cristal de cuarzo hialino. Piezoeléctrico y fuente de silicio de alta pureza.');
I('amethyst', 'Amatista', 'crystal', 3, '#9a78b8', 'Cuarzo violeta de geoda. Resonadores y óptica de precisión.');
I('bauxite', 'Bauxita', 'ore', 3, '#b06e4a', 'Óxido de aluminio hidratado. Se digiere en sosa para obtener alúmina.');
I('chromite', 'Cromita', 'ore', 3, '#5c5c58', 'Espinela de cromo y hierro. Cromo para inoxidables y refractarios.');
I('manganese_ore', 'Mena de manganeso', 'ore', 3, '#6a5a66', 'Pirolusita. Desoxidante y endurecedor del acero.');
I('natural_gas', 'Gas natural', 'gas', 4, '#b8b8a8', 'Metano de bolsas profundas. Combustible de turbina y fuente de hidrógeno.', { fuel: 36 });
/* ── raw: L3 ── */
I('rutile', 'Rutilo', 'ore', 5, '#7a5a48', 'Dióxido de titanio cristalino. Se clora y se reduce en horno de arco.');
I('wolframite', 'Wolframita', 'ore', 5, '#4a4640', 'Tungstato de hierro y manganeso. Tungsteno para filamentos y carburos.');
I('platinum_ore', 'Mena de platino', 'ore', 5, '#a8aaac', 'Esperrilita con trazas de iridio y osmio. Catalizadores y electrodos.');
I('cobalt_ore', 'Mena de cobalto', 'ore', 5, '#5c6a9a', 'Cobaltita. Superaleaciones e imanes de alta temperatura.');
I('spodumene', 'Espodumena', 'ore', 5, '#a8a0b0', 'Silicato de litio. Celdas de litio y cría de tritio.');
I('molybdenite', 'Molibdenita', 'ore', 5, '#6a6e78', 'Sulfuro de molibdeno laminar. Aceros de alta resistencia térmica.');
I('vanadinite', 'Vanadinita', 'ore', 5, '#b06040', 'Vanadato de plomo. Vanadio para aceros de herramienta.');
I('monazite', 'Monacita', 'ore', 5, '#a88a5a', 'Fosfato de tierras raras con torio. Imanes de neodimio y combustible de torio.');
I('uraninite', 'Uraninita', 'ore', 5, '#4a4e3a', 'Pechblenda. Uranio para la cadena de fisión.');
I('thorite', 'Torita', 'ore', 5, '#6a5a3a', 'Silicato de torio. Combustible fértil de reactor.');
I('fluorite', 'Fluorita', 'raw', 5, '#7ab8a0', 'Fluoruro cálcico. Fuente de ácido fluorhídrico para la conversión del uranio.');
I('diamond_raw', 'Diamante en bruto', 'crystal', 5, '#d8e0e4', 'Diamante kimberlítico sin tallar. Puntas de corte y ventanas ópticas.');
I('ruby_raw', 'Rubí en bruto', 'crystal', 5, '#b04858', 'Corindón rojo sin tallar. Medio activo de láser.');
I('sapphire_raw', 'Zafiro en bruto', 'crystal', 5, '#4a6aa0', 'Corindón azul sin tallar. Lentes y sustratos resistentes.');
I('obsidian', 'Obsidiana', 'raw', 5, '#2a262c', 'Vidrio volcánico. Se refunde en vidrio de calidad.');
I('basalt', 'Basalto', 'raw', 5, '#4a4a48', 'Roca ígnea densa. Losas térmicas y áridos refractarios.');
/* ── raw: L4 ── */
I('iridium_ore', 'Mena de iridio', 'ore', 7, '#9aa0a8', 'Aleación nativa Ir-Os del núcleo. El metal más resistente a la corrosión.');
I('osmium_ore', 'Mena de osmio', 'ore', 7, '#5a6a80', 'Osmiridio denso. Electrodos de plasma y contactos extremos.');
I('corestone', 'Piedra del núcleo', 'exotic', 7, '#8a3a5a', 'Mineral cristalizado a presión de manto. Base de la aleación del núcleo.');
I('plasma_crystal', 'Cristal de plasma', 'crystal', 7, '#b070d0', 'Cristal que confina plasma metaestable. Fuente de las celdas de plasma.');
I('neutronium_ore', 'Mena de neutronio', 'ore', 7, '#3a3450', 'Materia degenerada atrapada en roca. Solo la nanoforja la consolida.');
I('magma', 'Magma', 'fluid', 7, '#c85a2a', 'Roca fundida del mar de magma. Templada da basalto y obsidiana.');
I('deuterium_brine', 'Salmuera de deuterio', 'fluid', 6, '#6a9ab0', 'Salmuera profunda enriquecida en agua pesada. Se separa por criodestilación.');
I('helium3', 'Helio-3', 'gas', 7, '#e0d8f0', 'Isótopo ligero de helio de las chimeneas del núcleo. Combustible de fusión aneutrónica.');
/* ── farms & drops ── */
I('algae', 'Algas', 'organic', 4, '#5a7a3a', 'Biomasa de microalgas del estanque. Fuente de biocombustible y etanol.');
I('rubber_sap', 'Látex', 'fluid', 4, '#e0dcc8', 'Látex natural del invernadero. Vulcanizado con azufre da caucho.');
I('chitin', 'Quitina', 'organic', 2, '#7a6a50', 'Exoesqueleto de artrópodos de cueva. Biopolímero convertible en plástico.');
I('crystal_shard', 'Fragmento de cristal', 'crystal', 3, '#8ab0c8', 'Esquirla de las criaturas cristalinas. Ópticamente perfecta.');
I('heat_gland', 'Glándula térmica', 'organic', 5, '#c86a3a', 'Órgano refractario de la fauna abisal. Aísla placas contra el calor del núcleo.');
I('void_essence', 'Esencia del vacío', 'exotic', 7, '#5a3a7a', 'Residuo de los entes del vacío. Contiene plasma en estado no clásico.');

/* ── early crafted (T0–T2) ── */
I('plank', 'Tablón', 'building', 0, '#b08a5a', 'Tabla aserrada de tronco. Estructura de máquinas y edificios primitivos.', { fuel: 4 });
I('rope', 'Cuerda', 'part', 0, '#a89868', 'Fibra vegetal torcida en tres cabos. Ligaduras, poleas y transmisiones.');
I('cloth', 'Tela', 'organic', 0, '#c8bca0', 'Tejido basto de fibra vegetal. Filtros, velas y aislamiento de hilo.');
I('leather', 'Cuero', 'organic', 0, '#8a5a3a', 'Piel curtida con taninos vegetales. Fuelles, correas y juntas.');
I('charcoal', 'Carbón vegetal', 'fuel', 0, '#3a3634', 'Madera pirolizada en la carbonera. Combustible limpio y reductor de fundición.', { fuel: 16 });
I('wooden_gear', 'Engranaje de madera', 'gear', 0, '#a8845a', 'Rueda dentada tallada en tablón. Transmisión de baja carga.');
I('wood_frame', 'Bastidor de madera', 'building', 0, '#9a7a50', 'Marco de tablones ensamblado con cuerda. Chasis de las primeras máquinas.');
I('hand_tool', 'Herramienta de mano', 'part', 0, '#7a6a58', 'Cabeza de sílex enmangada en vara. Equipa recolectores y canteros.');
I('bellows', 'Fuelle', 'part', 0, '#8a6848', 'Cuero y tablones que insuflan aire al horno. Eleva la temperatura de fusión.');
I('brick', 'Ladrillo', 'building', 0, '#a05a44', 'Arcilla cocida en horno. Muros y revestimiento de hornos.');
I('ceramic', 'Cerámica', 'building', 0, '#c8a888', 'Arcilla y arena vitrificadas. Aislante eléctrico y térmico.');
I('glass', 'Vidrio', 'building', 1, '#a8c0c0', 'Sílice fundida y enfriada. Ventanas, lentes y recipientes.');
I('bone_meal', 'Harina de hueso', 'organic', 1, '#e0d8c0', 'Hueso molido. Fosfato para fertilizante.');
I('fertilizer', 'Fertilizante', 'organic', 2, '#8a7a4a', 'Mezcla de fosfato y nitrato. Acelera viveros y plantaciones.');
I('black_powder', 'Pólvora negra', 'chemical', 2, '#2a2826', 'Carbón, azufre y salitre molidos. Propelente de munición.');
I('quicklime', 'Cal viva', 'chemical', 2, '#e8e4d8', 'Óxido de calcio de caliza calcinada. Base de cemento y fundente.');
I('cement', 'Cemento', 'building', 2, '#b8b4a8', 'Clínker de cal y arcilla molido. Aglomerante hidráulico.');
I('concrete', 'Hormigón', 'building', 3, '#9a9890', 'Cemento, árido y agua fraguados. Cimentación de maquinaria pesada.');
I('reinforced_concrete', 'Hormigón armado', 'building', 4, '#84867e', 'Hormigón con armadura de acero. Vasijas, torres y muros pesados.');
I('refractory_brick', 'Ladrillo refractario', 'building', 4, '#b07858', 'Arcilla con alúmina cocida. Reviste hornos de arco y vacío.');
I('basalt_slab', 'Losa de basalto', 'building', 5, '#5a5a58', 'Basalto prensado y recocido. Solera de plantas geotérmicas y muros térmicos.');
I('coke', 'Coque', 'fuel', 2, '#3a3a3c', 'Carbón destilado sin aire. Reductor del alto horno y combustible denso.', { fuel: 30 });
I('bitumen', 'Betún', 'chemical', 3, '#2e2a28', 'Residuo pesado de destilación. Aglomerante de electrodos de grafito.');
I('graphite', 'Grafito', 'chemical', 4, '#4a4c50', 'Carbono cristalizado en horno. Electrodos, ánodos y precursor del grafeno.');
I('graphite_electrode', 'Electrodo de grafito', 'part', 4, '#3a3c40', 'Barra de grafito prensada y cocida. Se consume en arco y electrólisis.');

/* ── crushed ores ── */
const CR = (id, name, color, tier, src) => I(id, name, 'crushed', tier, color, src + ' triturada a grano fino. Lista para lavar o fundir.');
CR('crushed_copper', 'Cobre triturado', '#a8886a', 0, 'Mena de cobre');
CR('crushed_tin', 'Estaño triturado', '#9c9a94', 0, 'Casiterita');
CR('crushed_iron', 'Hierro triturado', '#9a7a66', 1, 'Mena de hierro');
CR('crushed_zinc', 'Zinc triturado', '#9aa0a6', 3, 'Esfalerita');
CR('crushed_lead', 'Plomo triturado', '#7e7c84', 3, 'Galena');
CR('crushed_silver', 'Plata triturada', '#c0c0c4', 3, 'Argentita');
CR('crushed_gold', 'Oro triturado', '#c0a85a', 3, 'Cuarzo aurífero');
CR('crushed_nickel', 'Níquel triturado', '#9ea090', 3, 'Pentlandita');
CR('crushed_chromite', 'Cromita triturada', '#6c6c68', 3, 'Cromita');
CR('crushed_manganese', 'Manganeso triturado', '#7a6a76', 3, 'Pirolusita');
CR('crushed_bauxite', 'Bauxita triturada', '#bc7e5a', 3, 'Bauxita');
CR('crushed_rutile', 'Rutilo triturado', '#8a6a58', 5, 'Rutilo');
CR('crushed_wolframite', 'Wolframita triturada', '#5a5650', 5, 'Wolframita');
CR('crushed_platinum', 'Platino triturado', '#b4b6b8', 5, 'Esperrilita');
CR('crushed_cobalt', 'Cobalto triturado', '#6c7aa8', 5, 'Cobaltita');
CR('crushed_spodumene', 'Espodumena triturada', '#b4acbc', 5, 'Espodumena');
CR('crushed_molybdenite', 'Molibdenita triturada', '#7a7e88', 5, 'Molibdenita');
CR('crushed_vanadinite', 'Vanadinita triturada', '#bc7050', 5, 'Vanadinita');
CR('crushed_monazite', 'Monacita triturada', '#b49a6a', 5, 'Monacita');
CR('crushed_uraninite', 'Uraninita triturada', '#5a5e4a', 5, 'Pechblenda');
CR('crushed_thorite', 'Torita triturada', '#7a6a4a', 5, 'Torita');
CR('crushed_iridium', 'Iridio triturado', '#a8aeb6', 7, 'Mena de iridio');
CR('crushed_osmium', 'Osmio triturado', '#6a7a90', 7, 'Osmiridio');
CR('crushed_neutronium', 'Neutronio triturado', '#4a4460', 7, 'Mena de neutronio');

/* ── purified (washed) ores ── */
const PU = (id, name, color, tier, by) => I(id, name, 'crushed', tier, color, 'Concentrado lavado y decantado. Funde más rápido; el lavado libera trazas de ' + by + '.');
PU('purified_copper', 'Cobre purificado', '#b8946a', 3, 'oro');
PU('purified_tin', 'Estaño purificado', '#acaaa2', 3, 'zinc');
PU('purified_iron', 'Hierro purificado', '#a88a72', 3, 'manganeso');
PU('purified_zinc', 'Zinc purificado', '#a8b0b6', 3, 'plomo y plata');
PU('purified_lead', 'Plomo purificado', '#8c8a94', 3, 'plata');
PU('purified_silver', 'Plata purificada', '#d0d0d4', 3, 'oro');
PU('purified_gold', 'Oro purificado', '#d0b862', 3, 'plata');
PU('purified_nickel', 'Níquel purificado', '#aeb0a0', 3, 'cobalto y platino');
PU('purified_platinum', 'Platino purificado', '#c4c6c8', 5, 'iridio y osmio');

/* ── ingots & alloys ── */
I('copper_ingot', 'Lingote de cobre', 'ingot', 0, '#b87a58', 'Cobre fundido en horno de piedra. Conductor base y componente del bronce.');
I('tin_ingot', 'Lingote de estaño', 'ingot', 0, '#c4c4c0', 'Estaño de baja fusión. Aleante del bronce y de la soldadura.');
I('bronze_ingot', 'Lingote de bronce', 'ingot', 1, '#b08650', 'Aleación 3:1 de cobre y estaño. Engranajes, tuberías y herramientas de la primera era.');
I('iron_ingot', 'Lingote de hierro', 'ingot', 1, '#a8a49c', 'Hierro reducido con carbón. Base de placas, varillas y del acero.');
I('steel_ingot', 'Lingote de acero', 'ingot', 2, '#8c9098', 'Hierro carburado en alto horno con coque. Material estructural de la era del vapor.');
I('zinc_ingot', 'Lingote de zinc', 'ingot', 3, '#b8bcc0', 'Zinc destilado. Galvanizado y latón.');
I('brass_ingot', 'Lingote de latón', 'ingot', 3, '#c4a850', 'Cobre y zinc 3:1. Casquillos, válvulas e instrumentos.');
I('lead_ingot', 'Lingote de plomo', 'ingot', 3, '#7a7a80', 'Plomo blando y denso. Blindaje radiológico, soldadura y acumuladores.');
I('silver_ingot', 'Lingote de plata', 'ingot', 3, '#d0d0d4', 'Plata refinada. Contactos, resonadores y barras de control.');
I('gold_ingot', 'Lingote de oro', 'ingot', 3, '#d4b64a', 'Oro refinado. Hilo de contacto inoxidable para circuitos.');
I('electrum_ingot', 'Lingote de electro', 'ingot', 3, '#d0c070', 'Aleación de oro y plata. Contactos de alta conductividad más económicos que el oro puro.');
I('nickel_ingot', 'Lingote de níquel', 'ingot', 3, '#a8aca0', 'Níquel refinado. Aleante de inoxidables y superaleaciones.');
I('chromium_ingot', 'Lingote de cromo', 'ingot', 3, '#b8c0c4', 'Cromo reducido de cromita. Da resistencia a la corrosión.');
I('manganese_ingot', 'Lingote de manganeso', 'ingot', 3, '#8a7a8a', 'Manganeso metálico. Desoxidante y endurecedor del acero.');
I('stainless_ingot', 'Lingote de acero inoxidable', 'ingot', 3, '#c0c4c8', 'Acero con cromo y níquel. Química, vasijas y tuberías de presión.');
I('silicon_ingot', 'Lingote de silicio', 'ingot', 3, '#6a6e78', 'Silicio metalúrgico reducido con coque. Se corta en obleas.');
I('aluminium_ingot', 'Lingote de aluminio', 'ingot', 4, '#d0d4d8', 'Aluminio electrolítico. Ligero, conductor y resistente a la corrosión.');
I('cobalt_ingot', 'Lingote de cobalto', 'ingot', 5, '#6a78a8', 'Cobalto refinado. Superaleaciones y barras de control.');
I('vanadium_ingot', 'Lingote de vanadio', 'ingot', 5, '#9aa090', 'Vanadio reducido. Aceros de herramienta y aleaciones de titanio.');
I('titanium_ingot', 'Lingote de titanio', 'ingot', 5, '#9aa0a8', 'Titanio reducido del tetracloruro en arco. Ligero y resistente a alta temperatura.');
I('tungsten_ingot', 'Lingote de tungsteno', 'ingot', 5, '#6a6c70', 'Tungsteno reducido con hidrógeno. El metal de mayor punto de fusión.');
I('tungsten_carbide', 'Carburo de tungsteno', 'ingot', 5, '#4a4c50', 'Tungsteno carburizado en vacío. Puntas de perforación y blindaje.');
I('platinum_ingot', 'Lingote de platino', 'ingot', 5, '#d8dadc', 'Platino refinado. Catalizadores y electrodos inertes.');
I('lithium_ingot', 'Lingote de litio', 'ingot', 5, '#c8ccc0', 'Litio electrolítico. Celdas de energía y cría de tritio.');
I('molybdenum_ingot', 'Lingote de molibdeno', 'ingot', 5, '#8a8e94', 'Molibdeno reducido. Resistencia térmica en superaleaciones.');
I('superalloy_ingot', 'Lingote de superaleación', 'ingot', 5, '#a89890', 'Níquel-cromo-cobalto-molibdeno fundido en vacío. Turbinas y vasijas de reactor.');
I('thorium_ingot', 'Lingote de torio', 'ingot', 6, '#8a8a70', 'Torio metálico. Combustible fértil.');
I('iridium_ingot', 'Lingote de iridio', 'ingot', 7, '#c0c4c8', 'Iridio consolidado en arco. Inatacable por el calor y la corrosión del núcleo.');
I('osmium_ingot', 'Lingote de osmio', 'ingot', 7, '#7a8aa0', 'Osmio consolidado. Electrodos de inyección de plasma.');
I('neutronium_ingot', 'Lingote de neutronio', 'ingot', 7, '#5a5070', 'Materia degenerada estabilizada en la nanoforja. Densidad extrema.');
I('core_alloy', 'Aleación del núcleo', 'ingot', 7, '#7a4a60', 'Piedra del núcleo aleada con iridio y carburo. Estructura de las máquinas del núcleo.');

/* ── chemicals & solid intermediates ── */
I('alumina', 'Alúmina', 'chemical', 4, '#e4e0d8', 'Óxido de aluminio purificado de la bauxita. Se electroliza en aluminio.');
I('tungsten_oxide', 'Óxido de tungsteno', 'chemical', 5, '#c8c860', 'Trióxido de tungsteno amarillo. Se reduce con hidrógeno.');
I('rare_earth_oxide', 'Óxido de tierras raras', 'chemical', 5, '#b8a880', 'Concentrado de neodimio y lantánidos de la monacita. Imanes permanentes.');
I('plastic', 'Plástico', 'chemical', 4, '#d8d0c0', 'Polietileno polimerizado de nafta. Aislantes, carcasas y placas de circuito.');
I('rubber', 'Caucho', 'chemical', 4, '#3a3634', 'Látex o nafta vulcanizados con azufre. Juntas, correas y aislamiento.');
I('solder', 'Soldadura', 'part', 1, '#c8c8c0', 'Estaño, o estaño y plomo, de baja fusión. Une componentes en los circuitos.');
I('yellowcake', 'Torta amarilla', 'nuclear', 5, '#d8c030', 'Concentrado de uranio lixiviado con ácido sulfúrico. Se convierte en hexafluoruro.');
I('uranium_pellet', 'Pastilla de uranio', 'nuclear', 6, '#5a5a48', 'Dióxido de uranio enriquecido sinterizado. Se apila en barras de combustible.');
I('fuel_rod', 'Barra de combustible', 'nuclear', 6, '#8a9060', 'Pastillas de uranio en vaina de inoxidable. Combustible del reactor de fisión.', { fuel: 4e5 });
I('depleted_uranium', 'Uranio empobrecido', 'nuclear', 6, '#4a4e40', 'Uranio residual del enriquecimiento. Material fértil para MOX.');
I('spent_fuel', 'Combustible gastado', 'nuclear', 6, '#6a7a3a', 'Barra irradiada con plutonio y productos de fisión. Se reprocesa con ácido nítrico.');
I('plutonium', 'Plutonio', 'nuclear', 6, '#8a9a40', 'Plutonio recuperado por reprocesamiento. Fisible para MOX y semilla de torio.');
I('mox_rod', 'Barra MOX', 'nuclear', 6, '#8a8a50', 'Óxido mixto de plutonio y uranio empobrecido. Mayor rendimiento que el uranio.', { fuel: 5e5 });
I('thorium_fuel', 'Combustible de torio', 'nuclear', 6, '#7a8a5a', 'Torio con semilla de uranio en vaina. Combustible fértil de larga duración.', { fuel: 3e5 });
I('fusion_pellet', 'Pastilla de fusión', 'nuclear', 7, '#a0c8e0', 'Deuterio y tritio criogénicos encapsulados. Combustible del reactor de fusión.', { fuel: 6e6 });
I('he3_pellet', 'Pastilla de helio-3', 'nuclear', 7, '#c0b0e0', 'Helio-3 y deuterio encapsulados. Fusión aneutrónica de máximo rendimiento.', { fuel: 9e6 });

/* ── plates, rods, gears, wires, pipes, frames ── */
I('copper_plate', 'Placa de cobre', 'plate', 0, '#c89a78', 'Cobre batido en placa. Conductores y contactos.');
I('bronze_plate', 'Placa de bronce', 'plate', 1, '#c0a070', 'Bronce forjado en placa. Carcasas y cubiertas de la era mecánica.');
I('iron_plate', 'Placa de hierro', 'plate', 1, '#b8b4ac', 'Hierro forjado en placa. Estructura y blindaje ligero.');
I('steel_plate', 'Placa de acero', 'plate', 2, '#a4a8b0', 'Acero laminado. Calderas, bastidores y muros.');
I('lead_plate', 'Placa de plomo', 'plate', 3, '#8c8c92', 'Plomo laminado. Blindaje contra radiación y placas de acumulador.');
I('stainless_plate', 'Placa de inoxidable', 'plate', 3, '#d0d4d8', 'Inoxidable laminado. Reactores químicos y vasijas.');
I('aluminium_plate', 'Placa de aluminio', 'plate', 4, '#e0e4e8', 'Aluminio laminado. Carcasas ligeras y condensadores.');
I('titanium_plate', 'Placa de titanio', 'plate', 5, '#b0b6be', 'Titanio laminado. Tanques criogénicos y muros de alta resistencia.');
I('tungsten_plate', 'Placa de tungsteno', 'plate', 5, '#7c7e84', 'Tungsteno prensado en caliente. Escudos térmicos.');
I('superalloy_plate', 'Placa de superaleación', 'plate', 5, '#b8a8a0', 'Superaleación laminada. Cámaras de turbina y reactores.');
I('bronze_rod', 'Varilla de bronce', 'rod', 1, '#b09060', 'Bronce forjado en varilla. Ejes y pasadores.');
I('iron_rod', 'Varilla de hierro', 'rod', 1, '#a8a49c', 'Hierro forjado en varilla. Ejes, armaduras y proyectiles.');
I('steel_rod', 'Varilla de acero', 'rod', 2, '#94989e', 'Acero forjado en varilla. Ejes de máquina y armadura del hormigón.');
I('titanium_rod', 'Varilla de titanio', 'rod', 5, '#a0a6ae', 'Titanio torneado. Ejes de alta velocidad.');
I('tungsten_rod', 'Varilla de tungsteno', 'rod', 5, '#707278', 'Tungsteno sinterizado en varilla. Electrodos y filamentos.');
I('bronze_gear', 'Engranaje de bronce', 'gear', 1, '#b89058', 'Rueda dentada de bronce. Transmisiones mecánicas de la primera era.');
I('iron_gear', 'Engranaje de hierro', 'gear', 1, '#aaa69e', 'Rueda dentada de hierro forjado. Transmisiones de carga media.');
I('steel_gear', 'Engranaje de acero', 'gear', 2, '#9498a0', 'Rueda dentada de acero. Reductores de la maquinaria pesada.');
I('titanium_gear', 'Engranaje de titanio', 'gear', 5, '#a4aab2', 'Rueda dentada de titanio. Fabricadores y turbinas de precisión.');
I('copper_wire', 'Hilo de cobre', 'wire', 1, '#c88a60', 'Cobre estirado en hilo. Bobinas, cables y circuitos.');
I('insulated_wire', 'Cable aislado', 'wire', 2, '#8a5a48', 'Hilo de cobre forrado de tela y resina. Cableado de baja tensión.');
I('gold_wire', 'Hilo de oro', 'wire', 3, '#dcc060', 'Oro estirado en hilo fino. Contactos de circuitos avanzados.');
I('aluminium_wire', 'Hilo de aluminio', 'wire', 4, '#dce0e4', 'Aluminio estirado. Conductores de alta tensión.');
I('tungsten_wire', 'Hilo de tungsteno', 'wire', 5, '#808288', 'Filamento de tungsteno. Emisores térmicos y sensores.');
I('superconductor_wire', 'Hilo superconductor', 'wire', 7, '#8a7ab8', 'Cerámica superconductora en matriz de plata. Resistencia nula bajo nitrógeno líquido.');
I('bronze_pipe', 'Tubo de bronce', 'part', 1, '#b48a58', 'Tubo de bronce. Canalización de fluidos a baja presión.');
I('steel_pipe', 'Tubo de acero', 'part', 2, '#8e9298', 'Tubo de acero soldado. Vapor y fluidos a presión.');
I('titanium_pipe', 'Tubo de titanio', 'part', 5, '#a4aab0', 'Tubo de titanio. Fluidos corrosivos y criogénicos.');
I('iron_frame', 'Bastidor de hierro', 'building', 1, '#9a9690', 'Perfiles de hierro remachados. Chasis de máquinas de vapor.');
I('steel_frame', 'Bastidor de acero', 'building', 2, '#84888e', 'Perfiles de acero soldados. Chasis de maquinaria eléctrica.');
I('titanium_frame', 'Bastidor de titanio', 'building', 5, '#9aa0a8', 'Perfiles de titanio. Chasis de maquinaria avanzada.');
I('core_frame', 'Bastidor del núcleo', 'building', 7, '#6a4058', 'Aleación del núcleo con placa térmica. Chasis de máquinas resistentes al calor del núcleo.');

/* ── mechanical parts & components ── */
I('mechanism', 'Mecanismo', 'component', 1, '#a08a60', 'Engranajes de bronce sobre eje en bastidor. Corazón de las máquinas mecánicas.');
I('drill_head', 'Cabezal de perforación', 'part', 2, '#7a7e84', 'Corona de acero dentada. Equipa perforadoras y tuneladoras.');
I('valve', 'Válvula', 'part', 2, '#b8a058', 'Válvula de bronce con vástago de hierro. Regula vapor y fluidos.');
I('piston', 'Pistón', 'part', 2, '#8c9098', 'Pistón de acero con junta de cuero. Motores de vapor y prensas.');
I('boiler', 'Caldera', 'component', 2, '#78787c', 'Cuerpo remachado de acero con tubos. Genera vapor a presión.');
I('bearing', 'Rodamiento', 'part', 3, '#a0a4aa', 'Anillos y bolas de acero torneadas. Ejes de alta velocidad.');
I('magnet', 'Imán', 'part', 3, '#5a5c66', 'Acero imantado. Motores, dinamos y sensores.');
I('electromagnet', 'Electroimán', 'part', 3, '#9a6a4a', 'Bobina de cobre sobre núcleo de hierro. Motores y separación magnética.');
I('motor', 'Motor eléctrico', 'component', 3, '#6a6e74', 'Estator bobinado y rotor imantado. Mueve toda la maquinaria eléctrica.');
I('dynamo', 'Dinamo', 'component', 3, '#7a6e64', 'Generador de bobinas e imanes. Convierte par en corriente.');
I('transformer_core', 'Núcleo de transformador', 'component', 3, '#7a7068', 'Chapas de hierro y bobinas aisladas. Distribución de alta tensión.');
I('turbine_blade', 'Álabe de turbina', 'part', 3, '#b0b4ba', 'Álabe prensado de acero. Ruedas de turbina.');
I('turbine', 'Turbina', 'component', 4, '#8c9098', 'Rotor de álabes sobre rodamientos. Turbinas de gas y vapor.');
I('pump_mechanism', 'Mecanismo de bomba', 'component', 3, '#8a8e94', 'Impulsor, válvula y eje. Bombas y balancines.');
I('heat_exchanger', 'Intercambiador de calor', 'component', 4, '#c0c4c8', 'Haz de tubos en carcasa de inoxidable. Refrigeración de plantas químicas y reactores.');
I('capacitor', 'Condensador', 'part', 4, '#d0c8b8', 'Láminas de aluminio y dieléctrico plástico. Almacena carga.');
I('battery_cell', 'Celda de acumulador', 'component', 3, '#6a6a70', 'Placas de plomo en caja de vidrio. Acumulación química de energía.');
I('lithium_cell', 'Celda de litio', 'component', 5, '#b8bcb0', 'Ánodo de grafito y cátodo de litio. Alta densidad de energía.');
I('crystal_oscillator', 'Oscilador de cuarzo', 'part', 3, '#d0ccc4', 'Cuarzo tallado en lámina resonante. Reloj de circuitos y sensores.');
I('sensor', 'Sensor', 'component', 4, '#7a8a80', 'Oscilador, circuito y bobina en carcasa. Instrumentación de máquinas y torretas.');
I('resonator', 'Resonador', 'component', 4, '#8a6aa0', 'Amatista con bobinas de plata. Circuitos de alta frecuencia y descarga.');
I('ruby', 'Rubí tallado', 'crystal', 5, '#c04858', 'Corindón rojo pulido en barra. Medio láser.');
I('sapphire', 'Zafiro tallado', 'crystal', 5, '#5a7ab0', 'Corindón azul pulido. Ventanas y sustratos.');
I('diamond', 'Diamante tallado', 'crystal', 5, '#e0e8ec', 'Diamante pulido. Puntas de corte y ventanas de alta presión.');
I('crystal_lens', 'Lente de cristal', 'part', 4, '#9ac0d0', 'Lente pulida de cristal óptico. Enfoca haces láser.');
I('laser_emitter', 'Emisor láser', 'component', 5, '#b05060', 'Barra de rubí, lente y banco de condensadores. Corte y defensa térmica.');
I('neodymium_magnet', 'Imán de neodimio', 'part', 5, '#5a5a70', 'Neodimio-hierro-boro sinterizado. Motores y dinamos compactos.');
I('carbide_tip', 'Punta de carburo', 'part', 5, '#3a3c42', 'Carburo de tungsteno con diamante. Perforación de roca abisal.');
I('thermal_plate', 'Placa térmica', 'plate', 6, '#b06040', 'Tungsteno, cerámica y tejido refractario. Aísla del calor del núcleo.');
I('control_rod', 'Barra de control', 'component', 6, '#a8a8b0', 'Aleación de plata y cobalto en vaina. Absorbe neutrones del reactor.');
I('reactor_vessel', 'Vasija de reactor', 'component', 6, '#8a8e94', 'Inoxidable, plomo y hormigón armado. Contiene el núcleo de fisión.');
I('containment_coil', 'Bobina de confinamiento', 'component', 7, '#7a6aa0', 'Superconductor sobre bastidor del núcleo. Confina el plasma de fusión.');
I('plasma_injector', 'Inyector de plasma', 'component', 7, '#9a70c0', 'Electrodos de osmio y lente. Inyecta combustible en el plasma.');
I('plasma_cell', 'Celda de plasma', 'exotic', 7, '#b088d8', 'Cristal de plasma cargado con hidrógeno líquido. Energía en estado no clásico.');
I('glass_fiber', 'Fibra de vidrio', 'part', 4, '#c8d4d8', 'Vidrio estirado en filamento. Aislamiento y fibra óptica.');
I('fiber_optic', 'Fibra óptica', 'component', 5, '#a8c8d8', 'Fibra de vidrio con recubrimiento plástico. Transmisión de datos y láser.');
I('silicon_wafer', 'Oblea de silicio', 'part', 4, '#4a5060', 'Disco cortado de lingote de silicio. Sustrato de circuitos.');
I('circuit_basic', 'Circuito básico', 'circuit', 2, '#6a8a6a', 'Relés y bobinas sobre placa de hierro. Control de máquinas eléctricas.');
I('circuit_advanced', 'Circuito avanzado', 'circuit', 4, '#5a7a7a', 'Oblea de silicio sobre placa plástica con hilo de oro. Control industrial.');
I('processor', 'Procesador', 'circuit', 5, '#4a6a7a', 'Obleas litografiadas y grabadas. Automatización avanzada.');
I('quantum_processor', 'Procesador cuántico', 'circuit', 7, '#7a5aa0', 'Grafeno y cristal de plasma sobre superconductor. Control de la era cuántica.');
I('graphene', 'Grafeno', 'exotic', 7, '#4a4a58', 'Lámina monoatómica de carbono exfoliada en la nanoforja. Conductor perfecto.');
I('nanotube', 'Nanotubo', 'exotic', 7, '#5a5a6a', 'Grafeno enrollado. Fibra de resistencia extrema.');

/* ── science & ammo ── */
I('rp0', 'Saber primitivo', 'science', 0, '#b8a888', 'Notas sobre corteza y sílex. Investigación de la edad de piedra.');
I('rp1', 'Ciencia básica', 'science', 1, '#b08a58', 'Cuadernos de mecánica con muestras de bronce e hilo. Investigación mecánica.');
I('rp2', 'Ciencia industrial', 'science', 2, '#7f8ea3', 'Ensayos de acero y circuitos. Investigación de vapor y electricidad.');
I('rp3', 'Ciencia química', 'science', 4, '#8fb87a', 'Muestras de polímeros, ácidos y circuitos. Investigación química.');
I('rp4', 'Ciencia nuclear', 'science', 6, '#c9a227', 'Pastillas, procesadores y refrigerante. Investigación nuclear.');
I('rp5', 'Ciencia cuántica', 'science', 7, '#b28cff', 'Procesadores cuánticos y celdas de plasma. Investigación de la era cuántica.');
I('arrow', 'Flecha', 'ammo', 0, '#8a7a5a', 'Astil de vara con punta de sílex. Munición de torres de vigía.');
I('ballista_bolt', 'Virote de balista', 'ammo', 1, '#8a8478', 'Varilla de hierro con astil de tablón. Munición de balista.');
I('cannon_shell', 'Proyectil de cañón', 'ammo', 3, '#6a6c70', 'Acero relleno de pólvora. Munición de torreta de cañón.');
I('bullet', 'Cartucho', 'ammo', 4, '#b8a050', 'Casquillo de latón con carga de pólvora. Munición de torreta automática.');

/* ── crafted fluids & gases ── */
I('naphtha', 'Nafta', 'fluid', 3, '#c8a860', 'Fracción ligera del crudo y del alquitrán. Materia prima de plásticos y caucho sintético.', { fuel: 38 });
I('diesel', 'Diésel', 'fluid', 3, '#b89a50', 'Fracción media del crudo. Combustible de generadores.', { fuel: 42 });
I('kerosene', 'Queroseno', 'fluid', 3, '#d8c080', 'Fracción intermedia del crudo. Combustible de generadores y lámparas.', { fuel: 40 });
I('lubricant', 'Lubricante', 'fluid', 3, '#c8b070', 'Aceite mineral o vegetal refinado. En la red de tuberías reduce el desgaste de las máquinas.');
I('tar', 'Alquitrán', 'fluid', 2, '#3a3630', 'Subproducto viscoso del horno de coque. Combustible pobre y fuente de nafta y betún.', { fuel: 20 });
I('sulfuric_acid', 'Ácido sulfúrico', 'fluid', 4, '#c8c880', 'Azufre oxidado y absorbido en agua. Lixiviación de menas y baterías.');
I('hydrochloric_acid', 'Ácido clorhídrico', 'fluid', 4, '#b8d0a0', 'Cloruro de hidrógeno en agua. Digestión de silicatos y limpieza de metales.');
I('nitric_acid', 'Ácido nítrico', 'fluid', 4, '#d8d090', 'Oxidación de amoniaco o salitre. Reprocesamiento nuclear y explosivos.');
I('hydrofluoric_acid', 'Ácido fluorhídrico', 'fluid', 5, '#b8d0b0', 'Fluorita digerida en ácido sulfúrico. Convierte el uranio en hexafluoruro y graba obleas.');
I('ammonia', 'Amoniaco', 'gas', 4, '#8ab0b8', 'Nitrógeno e hidrógeno combinados a presión. Fertilizante y ácido nítrico.');
I('chlorine', 'Cloro', 'gas', 4, '#b8c878', 'Gas de la electrólisis de salmuera. Cloración de titanio y ácido clorhídrico.');
I('hydrogen', 'Hidrógeno', 'gas', 4, '#c8d8e8', 'Gas ligero de electrólisis o reformado. Reductor, combustible y materia prima del amoniaco.', { fuel: 12 });
I('oxygen', 'Oxígeno', 'gas', 4, '#a8c8d8', 'Oxígeno separado del aire o del agua. Oxidante de ácidos y fundición.');
I('nitrogen', 'Nitrógeno', 'gas', 4, '#b8c0c8', 'Nitrógeno separado del aire. Amoniaco y atmósferas inertes.');
I('liquid_nitrogen', 'Nitrógeno líquido', 'fluid', 6, '#c8e0f0', 'Nitrógeno condensado a 77 K. Superconductores y perforación criogénica.');
I('liquid_hydrogen', 'Hidrógeno líquido', 'fluid', 6, '#d8e8f8', 'Hidrógeno condensado a 20 K. Carga de las celdas de plasma.');
I('ethanol', 'Etanol', 'fluid', 3, '#d8d8c0', 'Alcohol fermentado y destilado de biomasa. Combustible y precursor de bioplástico.', { fuel: 22 });
I('biofuel', 'Biocombustible', 'fluid', 4, '#8aa860', 'Aceite de algas transesterificado. Sustituto del diésel.', { fuel: 34 });
I('deuterium', 'Deuterio', 'fluid', 6, '#a8d0e8', 'Hidrógeno pesado separado de la salmuera. Combustible de fusión.');
I('tritium', 'Tritio', 'fluid', 6, '#a8e0c8', 'Hidrógeno radiactivo criado en litio. Combustible de fusión D-T.');
I('coolant', 'Refrigerante', 'fluid', 3, '#7ab8c8', 'Salmuera inhibida. Circuitos de refrigeración de maquinaria.');
I('cryo_coolant', 'Refrigerante criogénico', 'fluid', 6, '#a8d8e8', 'Refrigerante cargado con nitrógeno líquido. Enfría bobinas y láseres.');
I('uf6', 'Hexafluoruro de uranio', 'gas', 5, '#c8d890', 'Uranio natural en forma gaseosa. Alimenta la cascada de enriquecimiento.');
I('enriched_uf6', 'UF6 enriquecido', 'gas', 6, '#d8e070', 'Hexafluoruro con mayor fracción de U-235. Se convierte en pastillas.');
I('depleted_uf6', 'UF6 empobrecido', 'gas', 6, '#a8b088', 'Colas de la cascada. Se reduce a uranio empobrecido.');
I('compressed_air', 'Aire comprimido', 'gas', 4, '#d8dcd8', 'Aire atmosférico a presión. Se separa en nitrógeno y oxígeno.');
I('titanium_tetrachloride', 'Tetracloruro de titanio', 'fluid', 5, '#d8d0b0', 'Rutilo clorado. Se reduce a titanio en horno de arco.');

LD.Content.items = items;
})();
